// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   6 bus channels used by relic emits/reacts
// </auto-generated>

namespace RelicRun.Core.Content
{
    /// <summary>
    /// Event channels on the chain bus. A relic <c>emits</c> some and <c>reacts</c> to others;
    /// a relic is only "live" if something in the loadout can produce a channel it reacts to.
    /// </summary>
    public enum Channel
    {
        Dmg = 0,
        Gold = 1,
        Heal = 2,
        Hit = 3,
        Kill = 4,
        Luck = 5,
    }
}
