// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   10 halls
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One hall of the Hoard: what it is worth, and what its boss carries.</summary>
    public sealed class DungeonDef
    {
        /// <summary>Which hall this is, counting from one.</summary>
        public readonly int Tier;

        /// <summary>The delver level at which this hall is meant to be attempted.</summary>
        public readonly int Level;

        public readonly string Name;

        public readonly string Art;

        /// <summary>
        /// What a run in this hall is worth, applied to the foes inside it and to the score.
        /// </summary>
        /// <remarks>
        /// A table, not a formula. The first five entries are exact powers of 1.1 and the rest
        /// are rounded to four places — 1.6105 where the power is 1.61051 — so computing the
        /// power instead of reading this scores the deep halls a point out.
        /// </remarks>
        public readonly double Multiplier;

        /// <summary>The relic kit every boss in this hall carries.</summary>
        public readonly IReadOnlyList<RelicId> BossRelics;

        /// <summary>When set, the Ghoolem replaces this hall's bosses below the first floor.</summary>
        public readonly bool GhoolemBoss;

        public DungeonDef(int tier, int level, string name, string art, double multiplier,
            IReadOnlyList<RelicId> bossRelics, bool ghoolemBoss)
        {
            Tier = tier;
            Level = level;
            Name = name;
            Art = art;
            Multiplier = multiplier;
            BossRelics = bossRelics;
            GhoolemBoss = ghoolemBoss;
        }
    }

    /// <summary>The halls, in order.</summary>
    public static class DungeonCatalog
    {
        private static readonly RelicId[] NoRelics = new RelicId[0];

        public static readonly IReadOnlyList<DungeonDef> All = new List<DungeonDef>
        {
            new DungeonDef(1, 1, "The Hoard", "assets/hall-hoard.png", 1, NoRelics, false),
            new DungeonDef(2, 4, "The Verdant Rot", "assets/hall-moss.png", 1.1, new[] { RelicId.BerserkerCharm }, false),
            new DungeonDef(3, 7, "The Gilded Tomb", "assets/hall-tomb.png", 1.21, new[] { RelicId.WeightedDice }, false),
            new DungeonDef(4, 10, "The Cracked Seam", "assets/hall-mine.png", 1.331, new[] { RelicId.IronSkin, RelicId.BerserkerCharm }, false),
            new DungeonDef(5, 13, "The Jaguar Steps", "assets/hall-jungle.png", 1.4641, new[] { RelicId.SwiftBoots, RelicId.DuelistsOath }, false),
            new DungeonDef(6, 16, "The Sunken Watch", "assets/hall-sunken.png", 1.6105, new[] { RelicId.TrollMarrow, RelicId.LuckyClover }, false),
            new DungeonDef(7, 19, "The Ember Forge", "assets/hall-forge.png", 1.7716, new[] { RelicId.Whetstone, RelicId.BerserkerCharm }, true),
            new DungeonDef(8, 22, "The Frostbound Cells", "assets/hall-frost.png", 1.9487, new[] { RelicId.IronSkin, RelicId.TrollMarrow }, true),
            new DungeonDef(9, 25, "The Orrery", "assets/hall-orrery.png", 2.1436, new[] { RelicId.WeightedDice, RelicId.LuckyClover, RelicId.SwiftBoots }, false),
            new DungeonDef(10, 28, "The Hoard-King's Court", "assets/hall-throne.png", 2.3579, new[] { RelicId.BerserkerCharm, RelicId.WeightedDice, RelicId.Whetstone, RelicId.IronSkin }, false),
        };

        /// <summary>
        /// The hall at this tier, clamped to the ones that exist — which is what the source
        /// does everywhere it reads the table, so a saved tier past the end still resolves.
        /// </summary>
        public static DungeonDef Get(int tier)
        {
            int i = tier - 1;
            if (i < 0) i = 0;
            if (i >= All.Count) i = All.Count - 1;
            return All[i];
        }
    }
}
