// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   13 species on a 3x13 sheet
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One species in the bestiary: what it is called, and where it is drawn.</summary>
    public sealed class EnemyDef
    {
        /// <summary>Bestiary index. What the engine passes around.</summary>
        public readonly int Index;

        /// <summary>The source game's string id, e.g. "rat". Used to name its art.</summary>
        public readonly string Key;

        /// <summary>
        /// Which row of the sheet draws it — NOT the index. The two agree for two species.
        /// </summary>
        public readonly int SheetRow;

        /// <summary>The line the bestiary shows once a delver has met this species.</summary>
        /// <remarks>
        /// English in every locale, and the source says so itself: its comment over the array
        /// reads "EN, like the components". The species NAME is translated — key <c>en0</c>
        /// upward — and its card is not, which is a distinction worth keeping rather than
        /// tidying, because tidying it means inventing eight translations nobody wrote.
        ///
        /// Read from the source by <c>Tools/capture/foes.mjs</c>. Thirteen lines typed by hand
        /// is thirteen chances to drop a word, and a bestiary entry with a word missing still
        /// reads as a bestiary entry.
        /// </remarks>
        public readonly string Lore;

        public EnemyDef(int index, string key, int sheetRow, string lore)
        {
            Index = index;
            Key = key;
            SheetRow = sheetRow;
            Lore = lore;
        }
    }

    /// <summary>
    /// The bestiary, as far as drawing it is concerned.
    /// </summary>
    /// <remarks>
    /// Deliberately thin. Everything about how a species FIGHTS — which floor fields it, how it
    /// scales, which of them guards the King — is in <c>EnemyPackGenerator</c>, hand-ported
    /// against the corpus. This table exists so the art can be found without a second copy of
    /// the bestiary living in the Editor.
    /// </remarks>
    public static class EnemyCatalog
    {
        public static readonly IReadOnlyList<EnemyDef> All = new[]
        {
            new EnemyDef(0, "rat", 1,
                "It has survived a thousand delves by eating the evidence."),
            new EnemyDef(1, "bat", 0,
                "Echolocation, tuned exclusively to coin purses."),
            new EnemyDef(2, "skull", 3,
                "Someone's bad decision, still grinning about it."),
            new EnemyDef(3, "slime", 2,
                "The dungeon's janitor. It does not distinguish trash from adventurer."),
            new EnemyDef(4, "wraith", 6,
                "What is left of a miner who counted his gold once too often."),
            new EnemyDef(5, "coin", 4,
                "It practiced being a coin for decades. The teeth still give it away."),
            new EnemyDef(6, "spider", 5,
                "Eight eyes, and every one of them on your purse."),
            new EnemyDef(7, "ogre", 11,
                "It guards the stair because the stair lost a bet."),
            new EnemyDef(8, "serpent", 10,
                "It swallowed a hoard once. Now the hoard does the thinking."),
            new EnemyDef(9, "crown", 12,
                "The Hoard-King does not spend. The Hoard-King only keeps."),
            new EnemyDef(10, "ghoolem", 9,
                "Ghoul packed into stone by something that wanted a door held. The stone won; the hunger stayed."),
            new EnemyDef(11, "eye", 7,
                "It does not guard the hoard. It audits it — and it already knows what you are carrying."),
            new EnemyDef(12, "husk", 8,
                "Delvers who never cashed out, walking home the long way. It carries nothing: the hoard has it all."),
        };

        /// <summary>What each sheet column shows: bare, armed, armed and shielded.</summary>
        /// <remarks>The King has no column of his own — he is drawn as a boss.</remarks>
        public static readonly IReadOnlyList<string> Ranks = new[]
        {
            "guard",
            "elite",
            "boss",
        };

        public const int SheetColumns = 3;
        public const int SheetRows = 13;

        /// <summary>Side of one cell, in pixels.</summary>
        public const int SheetCell = 64;

        public static EnemyDef Get(int index) { return All[index]; }

        /// <summary>The id its art is bound under: the key, then the rank it is drawn at.</summary>
        public static string ArtId(int index, int column)
        {
            return All[index].Key + "/" + Ranks[column];
        }
    }
}
