// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   13 species on a 3x13 sheet
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One species in the bestiary: what it is called, and where it is drawn.</summary>
    public sealed class EnemyDef
    {
        /// <summary>Bestiary index. What the engine passes around.</summary>
        public readonly int Index;

        /// <summary>The source game's string id, e.g. "rat". Used to name its art.</summary>
        public readonly string Key;

        /// <summary>
        /// Which row of the sheet draws it — NOT the index. The two agree for two species.
        /// </summary>
        public readonly int SheetRow;

        public EnemyDef(int index, string key, int sheetRow)
        {
            Index = index;
            Key = key;
            SheetRow = sheetRow;
        }
    }

    /// <summary>
    /// The bestiary, as far as drawing it is concerned.
    /// </summary>
    /// <remarks>
    /// Deliberately thin. Everything about how a species FIGHTS — which floor fields it, how it
    /// scales, which of them guards the King — is in <c>EnemyPackGenerator</c>, hand-ported
    /// against the corpus. This table exists so the art can be found without a second copy of
    /// the bestiary living in the Editor.
    /// </remarks>
    public static class EnemyCatalog
    {
        public static readonly IReadOnlyList<EnemyDef> All = new[]
        {
            new EnemyDef(0, "rat", 1),
            new EnemyDef(1, "bat", 0),
            new EnemyDef(2, "skull", 3),
            new EnemyDef(3, "slime", 2),
            new EnemyDef(4, "wraith", 6),
            new EnemyDef(5, "coin", 4),
            new EnemyDef(6, "spider", 5),
            new EnemyDef(7, "ogre", 11),
            new EnemyDef(8, "serpent", 10),
            new EnemyDef(9, "crown", 12),
            new EnemyDef(10, "ghoolem", 9),
            new EnemyDef(11, "eye", 7),
            new EnemyDef(12, "husk", 8),
        };

        /// <summary>What each sheet column shows: bare, armed, armed and shielded.</summary>
        /// <remarks>The King has no column of his own — he is drawn as a boss.</remarks>
        public static readonly IReadOnlyList<string> Ranks = new[]
        {
            "guard",
            "elite",
            "boss",
        };

        public const int SheetColumns = 3;
        public const int SheetRows = 13;

        /// <summary>Side of one cell, in pixels.</summary>
        public const int SheetCell = 64;

        public static EnemyDef Get(int index) { return All[index]; }

        /// <summary>The id its art is bound under: the key, then the rank it is drawn at.</summary>
        public static string ArtId(int index, int column)
        {
            return All[index].Key + "/" + Ranks[column];
        }
    }
}
