// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   prose for 12 dungeon events
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One thing a delver can do about an event, as the screen words it.</summary>
    public sealed class EventChoiceText
    {
        /// <summary>What the button says. English.</summary>
        public readonly string Label;

        /// <summary>
        /// The line under it, or empty.
        /// </summary>
        /// <remarks>
        /// Everything a gold cost cannot say: prices in health, in speed, in a coin flip. A
        /// choice that costs nothing and promises nothing has none.
        /// </remarks>
        public readonly string Hint;

        public EventChoiceText(string label, string hint)
        {
            Label = label;
            Hint = hint;
        }
    }

    /// <summary>Everything an event says, as the screen reads it out.</summary>
    public sealed class EventTextDef
    {
        /// <summary>The kicker over the art: MERCHANT, GAMBLE, TRAP and the rest. English.</summary>
        public readonly string Kicker;

        public readonly string Title;

        /// <summary>The paragraph under it. English.</summary>
        public readonly string Text;

        public readonly IReadOnlyList<EventChoiceText> Choices;

        public EventTextDef(string kicker, string title, string text,
            params EventChoiceText[] choices)
        {
            Kicker = kicker;
            Title = title;
            Text = text;
            Choices = choices;
        }
    }

    /// <summary>
    /// What the twelve events say.
    /// </summary>
    /// <remarks>
    /// The prose half of an event. What each choice DOES is <c>DungeonEvents</c>' and is
    /// hand-ported against the corpus; this is only what a delver reads, kept apart so that
    /// rewording a line can never reach a file that decides what a choice costs.
    ///
    /// English, like every other generated string in this project. The source ships these in its
    /// markup rather than its string table, so there is nothing to translate them from.
    /// </remarks>
    public static class EventText
    {
        /// <summary>Position is the event's index, as everything about events is.</summary>
        public static readonly IReadOnlyList<EventTextDef> All = new[]
        {
            new EventTextDef("MERCHANT", "The Pale Merchant", "A lantern gutters in an alcove. A hooded figure spreads a cloth: one relic, gleaming. \"Coin,\" it rasps, \"or something warmer.\"",
                new EventChoiceText("Buy the relic", "COSTS 60 GOLD"),
                new EventChoiceText("Pay in blood", "COSTS 20 HP"),
                new EventChoiceText("Walk away", "")),
            new EventTextDef("ENCOUNTER", "A Voice in the Dark", "Someone is trapped under fallen beams. \"Help me,\" they wheeze, \"and I will not forget it.\" Digging them out will cost you supplies.",
                new EventChoiceText("Help them", "COSTS 10 GOLD"),
                new EventChoiceText("Leave them", "")),
            new EventTextDef("GAMBLE", "Scratching in the Walls", "Behind the brickwork: skrit, skrit, skrit. Something is in there. Something, or someone's stash.",
                new EventChoiceText("Break the wall", ""),
                new EventChoiceText("Keep moving", "")),
            new EventTextDef("ENCOUNTER", "The Chained Ghost", "A translucent figure bars the path, dragging a locket on a chain. \"Carry it for me,\" it moans, \"and my shield is yours. It is... heavy.\"",
                new EventChoiceText("Take the locket", "+5 DEF · -5 SPD"),
                new EventChoiceText("Refuse", "")),
            new EventTextDef("ENCOUNTER", "Knife at Your Throat", "A thief drops from the ceiling, blade already out. \"The purse. Or we see what you're made of.\"",
                new EventChoiceText("Pay them off", "COSTS 15 GOLD"),
                new EventChoiceText("Fight!", "")),
            new EventTextDef("BLESSING", "The Glimmering Pool", "Water pools in a basin of pale stone, lit from below by nothing at all. It smells like rain from the world above.",
                new EventChoiceText("Drink deep", "+8 HP"),
                new EventChoiceText("Don't trust it", "")),
            new EventTextDef("TRAP", "Rusted Spike Trap", "The floor ahead is a carpet of rusted spikes, older than the dungeon's name. There is no way around.",
                new EventChoiceText("Pick across slowly", "-5 SPD"),
                new EventChoiceText("Leap it", "-6 HP")),
            new EventTextDef("GAMBLE", "The Imp's Dice", "An imp sits cross-legged on a barrel, rattling bone dice. \"Double or nothing, delver. The dice never lie. I do, but the dice never.\"",
                new EventChoiceText("Bet 15 gold", "50/50 · WIN +30"),
                new EventChoiceText("Decline", "")),
            new EventTextDef("ENCOUNTER", "Altar of the Deep", "A black altar, worn smooth by ten thousand palms. The groove down its center is stained a color you decide not to name.",
                new EventChoiceText("Offer blood", "-5 HP · +2 ATK"),
                new EventChoiceText("Pray quietly", "+3 HP")),
            new EventTextDef("GAMBLE", "The Glowing Mushroom", "A fist-sized mushroom pulses faint blue in the dark. Every delver knows the stories. Half of them end well.",
                new EventChoiceText("Eat it", ""),
                new EventChoiceText("Leave it", "")),
            new EventTextDef("MERCHANT", "The Dead Miner's Map", "A skeleton in a miner's helm clutches a folded chart. Its jaw hangs open, as if mid-bargain. A living voice from nowhere: \"Ten gold, and the good veins are yours.\"",
                new EventChoiceText("Buy the map", "COSTS 10 GOLD"),
                new EventChoiceText("Rob the dead", "FREE MAP · RISK A CURSE"),
                new EventChoiceText("Walk on", "")),
            new EventTextDef("CURSE", "A Chest, Unclaimed", "A banded chest sits in the open, unlocked, unguarded, in a dungeon that has never once been kind. It is exactly as suspicious as it looks.",
                new EventChoiceText("Open it", ""),
                new EventChoiceText("Leave it", "")),
        };

        public static EventTextDef Get(int index) { return All[index]; }
    }
}
