// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   art for 12 dungeon events
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>
    /// What each dungeon event is illustrated with, indexed as the events themselves are.
    /// </summary>
    /// <remarks>
    /// The rules half lives in <c>DungeonEvents</c> and is hand-ported against the corpus. This
    /// is only the picture, kept apart so that changing an illustration never touches a file
    /// that decides what a choice costs.
    /// </remarks>
    public static class EventArt
    {
        /// <summary>Art id per event index. Position is the event's index.</summary>
        public static readonly IReadOnlyList<string> All = new[]
        {
            "event-pale-merchant",
            "event-voice-dark",
            "event-scratching-walls",
            "event-chained-ghost",
            "event-knife-throat",
            "event-glimmering-pool",
            "event-rusted-spikes",
            "event-imps-dice",
            "event-altar-deep",
            "event-glowing-mushroom",
            "event-miners-map",
            "event-chest",
        };

        public static string Get(int index) { return All[index]; }
    }
}
