// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   9 states, 11 slots
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>
    /// The rig every hero pack is drawn against.
    /// </summary>
    /// <remarks>
    /// A pack supplies the ART; this supplies the shape of it — which slots exist, how long each
    /// animation runs, and what every role key means.
    ///
    /// A pack declares its own states too, and those are used to VALIDATE it: a part claiming
    /// more frames than its state allows is malformed. They are not what the game animates from.
    /// The registry decides that, and a pack drawn with more frames than the registry claims
    /// simply animates fully. Reading the pack's numbers instead is a mistake that changes every
    /// animation in the game and looks, at a glance, like the more obvious thing to do.
    /// </remarks>
    public static class HeroRig
    {
        /// <summary>The canvas a pack is drawn on unless it says otherwise.</summary>
        public const int DefaultSize = 32;

        /// <summary>The wardrobe slots, in the order the registry lists them.</summary>
        public static readonly IReadOnlyList<string> Slots = new List<string>
        {
            "bg",
            "back",
            "leg",
            "torso",
            "boot",
            "torsoProp",
            "armProp",
            "face",
            "head",
            "propL",
            "propR",
        };

        /// <summary>How long each state runs, and how it ends.</summary>
        public static readonly IReadOnlyDictionary<string, HeroStateDef> States =
            new Dictionary<string, HeroStateDef>
        {
            { "idle", new HeroStateDef { Frames = 1, Ms = 200, Mode = "loop" } },
            { "walk", new HeroStateDef { Frames = 4, Ms = 70, Mode = "loop" } },
            { "attack", new HeroStateDef { Frames = 3, Ms = 45, Mode = "once" } },
            { "hurt", new HeroStateDef { Frames = 1, Ms = 110, Mode = "once" } },
            { "spawn", new HeroStateDef { Frames = 4, Ms = 55, Mode = "once" } },
            { "jump", new HeroStateDef { Frames = 4, Ms = 50, Mode = "once" } },
            { "evade", new HeroStateDef { Frames = 3, Ms = 35, Mode = "once" } },
            { "block", new HeroStateDef { Frames = 2, Ms = 60, Mode = "hold" } },
            { "die", new HeroStateDef { Frames = 5, Ms = 65, Mode = "hold" } },
        };

        /// <summary>What each role key means, for anything that shows an artist the palette.</summary>
        public static readonly IReadOnlyDictionary<char, string> Roles =
            new Dictionary<char, string>
        {
            { '0', "accent-light" },
            { '1', "hair-light" },
            { '2', "skin-light" },
            { '3', "outfit-light" },
            { '4', "cape-light" },
            { '5', "face-light" },
            { '6', "steel-light" },
            { '7', "steel2-light" },
            { '8', "leather-light" },
            { '9', "gold-light" },
            { 'H', "hair" },
            { 'h', "hair-dark" },
            { 'K', "skin" },
            { 'k', "skin-dark" },
            { 'T', "outfit" },
            { 't', "outfit-dark" },
            { 'C', "cape" },
            { 'c', "cape-dark" },
            { 'A', "face" },
            { 'a', "face-dark" },
            { 'W', "steel" },
            { 'w', "steel-dark" },
            { 'S', "steel2" },
            { 's', "steel2-dark" },
            { 'B', "leather" },
            { 'e', "leather-dark" },
            { 'G', "gold" },
            { 'g', "gold-dark" },
            { 'R', "accent" },
            { 'r', "accent-dark" },
            { 'E', "eye" },
            { 'y', "eye-dark" },
            { 'Y', "eye-light" },
            { 'N', "eyebrow" },
            { 'n', "eyebrow-dark" },
            { 'M', "eyebrow-light" },
            { 'L', "highlight" },
            { 'l', "highlight-dark" },
            { 'J', "highlight-light" },
            { 'D', "shadow" },
            { 'u', "shadow-dark" },
            { 'U', "shadow-light" },
            { 'V', "wood" },
            { 'v', "wood-dark" },
            { 'q', "wood-light" },
            { 'F', "legs" },
            { 'b', "legs-dark" },
            { 'x', "legs-light" },
            { 'O', "boots" },
            { 'o', "boots-dark" },
            { '\u00b0', "boots-light" },
            { 'P', "white" },
            { 'Q', "black" },
            { 'd', "dark" },
            { '-', "grey 1" },
            { '_', "grey 2" },
            { '?', "grey 3" },
            { '/', "grey 4" },
            { '`', "grey 5" },
            { '!', "red" },
            { '(', "red-dark" },
            { ')', "red-light" },
            { '@', "orange" },
            { '[', "orange-dark" },
            { ']', "orange-light" },
            { '#', "yellow" },
            { '{', "yellow-dark" },
            { '}', "yellow-light" },
            { '$', "green" },
            { '<', "green-dark" },
            { '>', "green-light" },
            { '%', "blue" },
            { ';', "blue-dark" },
            { ':', "blue-light" },
            { '^', "teal" },
            { ',', "teal-dark" },
            { '\'', "teal-light" },
            { '&', "purple" },
            { '~', "purple-dark" },
            { '|', "purple-light" },
            { '*', "pink" },
            { '=', "pink-dark" },
            { '+', "pink-light" },
            { 'I', "brown" },
            { 'p', "brown-dark" },
            { '\u00b5', "brown-light" },
            { 'Z', "backdrop" },
            { 'z', "backdrop-dark" },
            { 'X', "backdrop-light" },
        };
    }
}
