// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   26 colour families
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One family of the palette: a base colour, and the two it derives.</summary>
    /// <remarks>
    /// The three keys are what a hero's pixels actually hold. A pixel saying <c>H</c> is hair,
    /// <c>h</c> is hair in shadow and <c>1</c> is hair catching the light — so recolouring a
    /// delver is a matter of handing the shader three different colours, not three sprites.
    /// </remarks>
    public sealed class ColourFamily
    {
        public readonly string Name;

        /// <summary>The key a pixel of the base colour carries.</summary>
        public readonly char Base;

        /// <summary>The key for the shaded side, derived from the base.</summary>
        public readonly char Dark;

        /// <summary>The key for the lit side, derived from the base.</summary>
        public readonly char Light;

        /// <summary>What the family is when the delver has chosen nothing.</summary>
        public readonly string DefaultHex;

        public ColourFamily(string name, char baseKey, char dark, char light, string defaultHex)
        {
            Name = name;
            Base = baseKey;
            Dark = dark;
            Light = light;
            DefaultHex = defaultHex;
        }
    }

    /// <summary>
    /// How far a family's derived colours move from its base.
    /// </summary>
    /// <remarks>
    /// Shared by every family unless one says otherwise, and exposed as data because the sprite
    /// studio lets an artist tune it and watch the whole wardrobe follow.
    /// </remarks>
    public sealed class ShadeParams
    {
        public double DarkMultiplier = 0.7;
        public double DarkHue = -12;
        public double DarkSaturation = 1.12;

        public double LightMultiplier = 1.32;
        public double LightHue = 10;
        public double LightSaturation = 0.9;
    }

    /// <summary>The families, the fixed colours, and the palette they make together.</summary>
    public static class HeroPalette
    {
        public static readonly IReadOnlyList<ColourFamily> Families = new List<ColourFamily>
        {
            new ColourFamily("Hair", 'H', 'h', '1', "#8A5A2B"),
            new ColourFamily("Skin", 'K', 'k', '2', "#F0C8A0"),
            new ColourFamily("Outfit", 'T', 't', '3', "#C4593C"),
            new ColourFamily("Cape", 'C', 'c', '4', "#4A6A8A"),
            new ColourFamily("Face", 'A', 'a', '5', "#8A5A2B"),
            new ColourFamily("Steel", 'W', 'w', '6', "#D7DCE3"),
            new ColourFamily("Leather", 'B', 'e', '8', "#5A4429"),
            new ColourFamily("Gold", 'G', 'g', '9', "#E3B341"),
            new ColourFamily("Accent", 'R', 'r', '0', "#E3B341"),
            new ColourFamily("Eye", 'E', 'y', 'Y', "#5C4632"),
            new ColourFamily("Eyebrow", 'N', 'n', 'M', "#4A3620"),
            new ColourFamily("Highlight", 'L', 'l', 'J', "#F2ECDD"),
            new ColourFamily("Shadow", 'D', 'u', 'U', "#3A3328"),
            new ColourFamily("Backdrop", 'Z', 'z', 'X', "#3A3A3E"),
            new ColourFamily("Wood", 'V', 'v', 'q', "#8A5A2B"),
            new ColourFamily("Legs", 'F', 'b', 'x', "#4A4436"),
            new ColourFamily("Boots", 'O', 'o', '\u00b0', "#5A4429"),
            new ColourFamily("Red", '!', '(', ')', "#D93A2B"),
            new ColourFamily("Orange", '@', '[', ']', "#E8842C"),
            new ColourFamily("Yellow", '#', '{', '}', "#F2C230"),
            new ColourFamily("Green", '$', '<', '>', "#4FA23C"),
            new ColourFamily("Blue", '%', ';', ':', "#2E7ED9"),
            new ColourFamily("Teal", '^', ',', '\'', "#28B5AD"),
            new ColourFamily("Purple", '&', '~', '|', "#8B5AC2"),
            new ColourFamily("Pink", '*', '=', '+', "#E06AA3"),
            new ColourFamily("Brown", 'I', 'p', '\u00b5', "#7A4A26"),
        };

        /// <summary>
        /// Colours that are never recoloured: white, black and five greys between them.
        /// </summary>
        public static readonly IReadOnlyDictionary<char, string> Fixed =
            new Dictionary<char, string>
        {
            { 'P', "#FFFFFF" },
            { 'Q', "#000000" },
            { '-', "#2E2E2E" },
            { '_', "#585858" },
            { '?', "#8A8A8A" },
            { '/', "#BDBDBD" },
            { '`', "#E8E8E8" },
        };

        /// <summary>
        /// The whole palette, as the shader wants it: every role key against its colour.
        /// </summary>
        /// <param name="chosen">
        /// A delver's own colours, keyed by a family's BASE key. Anything unstated keeps the
        /// family's default, which is how a half-dressed delver still comes out whole.
        /// </param>
        public static Dictionary<char, Rgb> Build(IReadOnlyDictionary<char, string> chosen = null,
            ShadeParams shade = null)
        {
            shade = shade ?? new ShadeParams();
            var roles = new Dictionary<char, Rgb>(Families.Count * 3 + Fixed.Count);

            for (int i = 0; i < Families.Count; i++)
            {
                ColourFamily family = Families[i];

                string picked;
                if (chosen == null || !chosen.TryGetValue(family.Base, out picked))
                {
                    picked = family.DefaultHex;
                }

                Rgb baseColour = Rgb.Parse(picked);
                roles[family.Base] = baseColour;
                roles[family.Dark] = HeroColour.ApplyShade(baseColour, shade.DarkMultiplier,
                    shade.DarkHue, shade.DarkSaturation);
                roles[family.Light] = HeroColour.ApplyShade(baseColour, shade.LightMultiplier,
                    shade.LightHue, shade.LightSaturation);
            }

            foreach (KeyValuePair<char, string> solo in Fixed)
            {
                roles[solo.Key] = Rgb.Parse(solo.Value);
            }

            return roles;
        }
    }
}
