// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   structural facts for 50 relics
// </auto-generated>

using System;
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>Which modes a relic may appear in.</summary>
    [Flags]
    public enum GameModes
    {
        None = 0,
        Delve = 1,
        Versus = 2,
        Both = Delve | Versus,
    }

    /// <summary>Structural definition of one relic. Immutable, generated from the source game.</summary>
    public sealed class RelicDef
    {
        public readonly RelicId Id;

        /// <summary>The source game's string id, e.g. "whetstone". Used by the corpus differ.</summary>
        public readonly string Key;

        public readonly RelicKind Kind;

        /// <summary>Whether a second copy adds a further effect rather than being wasted.</summary>
        public readonly bool Stackable;

        public readonly GameModes Modes;

        /// <summary>Channels this relic puts onto the bus when it activates.</summary>
        public readonly Channel[] Emits;

        /// <summary>Channels that activate this relic.</summary>
        public readonly Channel[] Reacts;

        /// <summary>The bus channel this relic natively listens on, if any.</summary>
        public readonly SocketTrigger NativeTrigger;

        public RelicDef(RelicId id, string key, RelicKind kind, bool stackable, GameModes modes,
            Channel[] emits, Channel[] reacts, SocketTrigger nativeTrigger)
        {
            Id = id;
            Key = key;
            Kind = kind;
            Stackable = stackable;
            Modes = modes;
            Emits = emits;
            Reacts = reacts;
            NativeTrigger = nativeTrigger;
        }
    }

    /// <summary>
    /// The relic table. Static and generated so that Core needs no JSON loading, no
    /// ScriptableObjects, and no Unity — which is what lets the engine be tested headlessly.
    /// </summary>
    public static class RelicCatalog
    {
        private static readonly Channel[] EmptyChannels = new Channel[0];

        public static readonly IReadOnlyList<RelicDef> All = new[]
        {
            new RelicDef(RelicId.Whetstone, "whetstone", RelicKind.Edge, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.OxHeart, "heart", RelicKind.Flesh, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.DebtOfFlesh, "debtflesh", RelicKind.Greed, false, GameModes.Both, new[] { Channel.Heal }, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.CoinMagnet, "magnet", RelicKind.Greed, true, GameModes.Both, new[] { Channel.Gold }, EmptyChannels, SocketTrigger.Kill),
            new RelicDef(RelicId.AlchemistsVial, "alchemist", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Heal }, new[] { Channel.Gold }, SocketTrigger.Gold),
            new RelicDef(RelicId.BloodAltar, "altar", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Dmg }, new[] { Channel.Heal }, SocketTrigger.None),
            new RelicDef(RelicId.ThornVest, "thorns", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Dmg }, new[] { Channel.Hit }, SocketTrigger.Hit),
            new RelicDef(RelicId.VampireTooth, "tooth", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Heal }, new[] { Channel.Hit }, SocketTrigger.Attack),
            new RelicDef(RelicId.MidasBlade, "midas", RelicKind.Edge, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.GreedyCurse, "greed", RelicKind.Curse, false, GameModes.Delve, EmptyChannels, EmptyChannels, SocketTrigger.Hit),
            new RelicDef(RelicId.SwiftBoots, "boots", RelicKind.Pace, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.BattleDash, "dash", RelicKind.Pace, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.LuckyClover, "clover", RelicKind.Luck, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.Dodge),
            new RelicDef(RelicId.IronSkin, "iron", RelicKind.Guard, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.AdrenalineGland, "adrenaline", RelicKind.Edge, false, GameModes.Both, EmptyChannels, new[] { Channel.Hit }, SocketTrigger.Hit),
            new RelicDef(RelicId.PiggyBank, "piggy", RelicKind.Greed, false, GameModes.Delve, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.BerserkerCharm, "berserk", RelicKind.Edge, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.RabbitsFoot, "rabbit", RelicKind.Luck, true, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.Luck),
            new RelicDef(RelicId.CutpurseHook, "cutpurse", RelicKind.Greed, false, GameModes.Both, new[] { Channel.Gold }, new[] { Channel.Luck }, SocketTrigger.Luck),
            new RelicDef(RelicId.WeightedDice, "dice", RelicKind.Luck, false, GameModes.Both, new[] { Channel.Dmg }, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.TrollMarrow, "marrow", RelicKind.Flesh, true, GameModes.Both, new[] { Channel.Heal }, new[] { Channel.Hit }, SocketTrigger.None),
            new RelicDef(RelicId.SecondStomach, "stomach", RelicKind.Flesh, false, GameModes.Delve, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.MartyrsKnot, "martyr", RelicKind.Flesh, true, GameModes.Both, EmptyChannels, new[] { Channel.Heal }, SocketTrigger.None),
            new RelicDef(RelicId.BloodPact, "bloodpact", RelicKind.Curse, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.GravekeepersSoil, "soil", RelicKind.Flesh, false, GameModes.Delve, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.PaddedHide, "hide", RelicKind.Flesh, true, GameModes.Both, EmptyChannels, new[] { Channel.Hit }, SocketTrigger.None),
            new RelicDef(RelicId.MirrorScale, "mirrorscale", RelicKind.Guard, false, GameModes.Both, new[] { Channel.Dmg }, new[] { Channel.Hit }, SocketTrigger.None),
            new RelicDef(RelicId.AnvilHeart, "anvil", RelicKind.Guard, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.SentinelBell, "sentinel", RelicKind.Guard, true, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.FortunesEdge, "fortunesedge", RelicKind.Edge, true, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.QuickenedPulse, "quickpulse", RelicKind.Pace, true, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.DuelistsOath, "duelist", RelicKind.Edge, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.QuenchedBlade, "quenched", RelicKind.Edge, false, GameModes.Both, EmptyChannels, new[] { Channel.Heal }, SocketTrigger.None),
            new RelicDef(RelicId.ExecutionersCoin, "executioner", RelicKind.Edge, true, GameModes.Both, new[] { Channel.Dmg }, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.WindAnklet, "windanklet", RelicKind.Pace, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.Stutterstep, "stutter", RelicKind.Pace, true, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.MomentumBead, "momentum", RelicKind.Pace, true, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.HaresDrum, "haredrum", RelicKind.Pace, false, GameModes.Both, EmptyChannels, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.LoadedHorseshoe, "horseshoe", RelicKind.Luck, true, GameModes.Both, new[] { Channel.Luck }, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.CatsWhisker, "catwhisker", RelicKind.Luck, false, GameModes.Both, new[] { Channel.Dmg }, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.FortunesDebt, "fortunedebt", RelicKind.Luck, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.TollkeepersRing, "tollring", RelicKind.Greed, true, GameModes.Both, new[] { Channel.Gold }, new[] { Channel.Kill }, SocketTrigger.None),
            new RelicDef(RelicId.MerchantsThumb, "merchantthumb", RelicKind.Greed, false, GameModes.Delve, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.GildedPlate, "auricskin", RelicKind.Guard, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.EmberCask, "embercask", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Gold }, new[] { Channel.Dmg }, SocketTrigger.None),
            new RelicDef(RelicId.CoinSinger, "coinsinger", RelicKind.Chain, false, GameModes.Both, new[] { Channel.Luck }, new[] { Channel.Gold }, SocketTrigger.None),
            new RelicDef(RelicId.HexThread, "hexthread", RelicKind.Chain, true, GameModes.Both, new[] { Channel.Dmg }, new[] { Channel.Luck }, SocketTrigger.None),
            new RelicDef(RelicId.HollowIdol, "hollowidol", RelicKind.Curse, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.FamineBell, "faminebell", RelicKind.Curse, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
            new RelicDef(RelicId.MillstonePendant, "millstone", RelicKind.Curse, false, GameModes.Both, EmptyChannels, EmptyChannels, SocketTrigger.None),
        };

        public const int Count = 50;

        private static readonly Dictionary<string, RelicId> ByKey = BuildKeyLookup();

        private static Dictionary<string, RelicId> BuildKeyLookup()
        {
            var map = new Dictionary<string, RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                map[All[i].Key] = All[i].Id;
            }

            return map;
        }

        public static RelicDef Get(RelicId id)
        {
            return All[(int)id];
        }

        public static RelicKind KindOf(RelicId id)
        {
            return All[(int)id].Kind;
        }

        /// <summary>Source-game string id for a relic, e.g. "whetstone".</summary>
        public static string KeyOf(RelicId id)
        {
            return All[(int)id].Key;
        }

        /// <summary>Resolve a source-game string id. Returns false for cut or unknown relics.</summary>
        public static bool TryParse(string key, out RelicId id)
        {
            return ByKey.TryGetValue(key, out id);
        }

        /// <summary>Relics that can appear in the given mode.</summary>
        public static List<RelicId> PoolFor(GameModes mode)
        {
            var pool = new List<RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                if ((All[i].Modes & mode) != 0)
                {
                    pool.Add(All[i].Id);
                }
            }

            return pool;
        }
    }
}
