// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   icon cells for 49 of 50 relics
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>Where one relic's icon comes from.</summary>
    public sealed class RelicArtDef
    {
        public readonly RelicId Id;

        /// <summary>Column on the icon sheet, or <c>-1</c> when there is no cell for it.</summary>
        public readonly int Column;

        /// <summary>Row on the icon sheet, or <c>-1</c>.</summary>
        public readonly int Row;

        /// <summary>
        /// The procedural glyph it falls back to, which every relic has whether it needs it or not.
        /// </summary>
        public readonly string Glyph;

        public RelicArtDef(RelicId id, int column, int row, string glyph)
        {
            Id = id;
            Column = column;
            Row = row;
            Glyph = glyph;
        }

        /// <summary>Whether an icon was drawn for it.</summary>
        public bool OnTheSheet { get { return Column >= 0; } }
    }

    /// <summary>
    /// The icon sheet, cell by cell.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules — nothing in the engine reads this. It is in Core so that the
    /// importer which slices <c>relic-icons.png</c> and the audit which checks the slices agree
    /// by construction, and so that both can be tested without opening the Editor.
    /// </remarks>
    public static class RelicArt
    {
        public const int SheetColumns = 10;
        public const int SheetRows = 8;

        /// <summary>Side of one cell, in pixels.</summary>
        public const int SheetCell = 48;

        public static readonly IReadOnlyList<RelicArtDef> All = new[]
        {
            new RelicArtDef(RelicId.Whetstone, 0, 2, "sword"),
            new RelicArtDef(RelicId.OxHeart, 0, 1, "heart"),
            new RelicArtDef(RelicId.DebtOfFlesh, -1, -1, "heart"),
            new RelicArtDef(RelicId.CoinMagnet, 0, 5, "magnet"),
            new RelicArtDef(RelicId.AlchemistsVial, 0, 7, "vial"),
            new RelicArtDef(RelicId.BloodAltar, 1, 7, "altar"),
            new RelicArtDef(RelicId.ThornVest, 2, 7, "thorns"),
            new RelicArtDef(RelicId.VampireTooth, 3, 7, "tooth"),
            new RelicArtDef(RelicId.MidasBlade, 1, 2, "crown"),
            new RelicArtDef(RelicId.GreedyCurse, 0, 6, "skull"),
            new RelicArtDef(RelicId.SwiftBoots, 0, 3, "boots"),
            new RelicArtDef(RelicId.BattleDash, 1, 3, "dash"),
            new RelicArtDef(RelicId.LuckyClover, 0, 4, "clover"),
            new RelicArtDef(RelicId.IronSkin, 0, 0, "shield"),
            new RelicArtDef(RelicId.AdrenalineGland, 2, 2, "bolt"),
            new RelicArtDef(RelicId.PiggyBank, 1, 5, "coin"),
            new RelicArtDef(RelicId.BerserkerCharm, 3, 2, "fist"),
            new RelicArtDef(RelicId.RabbitsFoot, 1, 4, "rabbit"),
            new RelicArtDef(RelicId.CutpurseHook, 2, 5, "purse"),
            new RelicArtDef(RelicId.WeightedDice, 2, 4, "dice"),
            new RelicArtDef(RelicId.TrollMarrow, 1, 1, "heart"),
            new RelicArtDef(RelicId.SecondStomach, 2, 1, "vial"),
            new RelicArtDef(RelicId.MartyrsKnot, 3, 1, "heart"),
            new RelicArtDef(RelicId.BloodPact, 1, 6, "altar"),
            new RelicArtDef(RelicId.GravekeepersSoil, 4, 1, "skull"),
            new RelicArtDef(RelicId.PaddedHide, 5, 1, "shield"),
            new RelicArtDef(RelicId.MirrorScale, 1, 0, "shield"),
            new RelicArtDef(RelicId.AnvilHeart, 2, 0, "fist"),
            new RelicArtDef(RelicId.SentinelBell, 3, 0, "shield"),
            new RelicArtDef(RelicId.FortunesEdge, 4, 2, "sword"),
            new RelicArtDef(RelicId.QuickenedPulse, 3, 3, "boots"),
            new RelicArtDef(RelicId.DuelistsOath, 7, 1, "sword"),
            new RelicArtDef(RelicId.QuenchedBlade, 5, 2, "sword"),
            new RelicArtDef(RelicId.ExecutionersCoin, 6, 2, "skull"),
            new RelicArtDef(RelicId.WindAnklet, 2, 3, "boots"),
            new RelicArtDef(RelicId.Stutterstep, 4, 3, "dash"),
            new RelicArtDef(RelicId.MomentumBead, 5, 3, "boots"),
            new RelicArtDef(RelicId.HaresDrum, 6, 3, "rabbit"),
            new RelicArtDef(RelicId.LoadedHorseshoe, 3, 4, "magnet"),
            new RelicArtDef(RelicId.CatsWhisker, 6, 1, "rabbit"),
            new RelicArtDef(RelicId.FortunesDebt, 4, 4, "dice"),
            new RelicArtDef(RelicId.TollkeepersRing, 3, 5, "coin"),
            new RelicArtDef(RelicId.MerchantsThumb, 4, 5, "purse"),
            new RelicArtDef(RelicId.GildedPlate, 4, 0, "coin"),
            new RelicArtDef(RelicId.EmberCask, 4, 7, "vial"),
            new RelicArtDef(RelicId.CoinSinger, 5, 7, "coin"),
            new RelicArtDef(RelicId.HexThread, 6, 7, "bolt"),
            new RelicArtDef(RelicId.HollowIdol, 2, 6, "skull"),
            new RelicArtDef(RelicId.FamineBell, 3, 6, "skull"),
            new RelicArtDef(RelicId.MillstonePendant, 4, 6, "fist"),
        };

        public static RelicArtDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
