// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   50 relics in the draft pool
// </auto-generated>

namespace RelicRun.Core.Content
{
    /// <summary>
    /// Every relic that can be drafted. Ordered as the source pool orders them.
    /// </summary>
    /// <remarks>
    /// This is the 50 reachable relics only. A further 28 have finished text and live code
    /// paths in the JS build but are absent from its draft table, so nothing can ever offer
    /// them; they are cut and recorded in docs/relics-cut.md.
    /// </remarks>
    public enum RelicId
    {
        None = -1,
        Whetstone = 0,
        OxHeart = 1,
        DebtOfFlesh = 2,
        CoinMagnet = 3,
        AlchemistsVial = 4,
        BloodAltar = 5,
        ThornVest = 6,
        VampireTooth = 7,
        MidasBlade = 8,
        GreedyCurse = 9,
        SwiftBoots = 10,
        BattleDash = 11,
        LuckyClover = 12,
        IronSkin = 13,
        AdrenalineGland = 14,
        PiggyBank = 15,
        BerserkerCharm = 16,
        RabbitsFoot = 17,
        CutpurseHook = 18,
        WeightedDice = 19,
        TrollMarrow = 20,
        SecondStomach = 21,
        MartyrsKnot = 22,
        BloodPact = 23,
        GravekeepersSoil = 24,
        PaddedHide = 25,
        MirrorScale = 26,
        AnvilHeart = 27,
        SentinelBell = 28,
        FortunesEdge = 29,
        QuickenedPulse = 30,
        DuelistsOath = 31,
        QuenchedBlade = 32,
        ExecutionersCoin = 33,
        WindAnklet = 34,
        Stutterstep = 35,
        MomentumBead = 36,
        HaresDrum = 37,
        LoadedHorseshoe = 38,
        CatsWhisker = 39,
        FortunesDebt = 40,
        TollkeepersRing = 41,
        MerchantsThumb = 42,
        GildedPlate = 43,
        EmberCask = 44,
        CoinSinger = 45,
        HexThread = 46,
        HollowIdol = 47,
        FamineBell = 48,
        MillstonePendant = 49,
    }
}
