// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   card text for 50 relics, English only
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>What one relic's card says about itself.</summary>
    public sealed class RelicLoreDef
    {
        public readonly RelicId Id;

        /// <summary>The line in quotes. Every relic has one.</summary>
        public readonly string Flavour;

        /// <summary>What it does with no prompting, or null when it does nothing by itself.</summary>
        public readonly string Passive;

        /// <summary>What sets it off, or null when nothing does.</summary>
        public readonly string Native;

        /// <summary>
        /// What it does when it goes off, or null when it never goes off.
        /// </summary>
        /// <remarks>
        /// The card labels this differently depending on <see cref="Native"/>: a relic with a
        /// trigger of its own says ON ACTIVATION, and one without says IF RELAYED — the same
        /// text, and a true difference, because the second only ever fires through a socket.
        /// </remarks>
        public readonly string Activation;

        /// <summary>What awakening it would do, or null for the eleven that cannot awaken.</summary>
        public readonly string Awake;

        public RelicLoreDef(RelicId id, string flavour, string passive, string native,
            string activation, string awake)
        {
            Id = id;
            Flavour = flavour;
            Passive = passive;
            Native = native;
            Activation = activation;
            Awake = awake;
        }
    }

    /// <summary>
    /// The relic dossiers.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules — nothing in the engine reads a word of this. What it describes
    /// is implemented in <c>Core/Run</c>, and the two can disagree without anything failing,
    /// which is the reason these lines are generated from the source rather than typed.
    /// </remarks>
    public static class RelicLore
    {
        public static readonly IReadOnlyList<RelicLoreDef> All = new[]
        {
            new RelicLoreDef(RelicId.Whetstone, "Every dawn it whispers the same word: sharper.", "+1 ATK, permanent.", null, "Hones the edge again: +1 ATK this floor.", "Strikes ignore enemy DEF."),
            new RelicLoreDef(RelicId.OxHeart, "Two sizes too big. Still warm.", "+13 max HP on pickup (and heals 13).", null, "Squeezes out 2 healing.", "Also heals 2 at each floor's gate."),
            new RelicLoreDef(RelicId.DebtOfFlesh, "The body remembers every coin that leaves.", "Spending gold heals 10.", null, null, "The debt pays double: heal 20."),
            new RelicLoreDef(RelicId.CoinMagnet, "Gold remembers where it belongs.", "Kill loot and coin spills: +1 gold each.", "Fires on every kill.", "Pulls in 2 gold.", null),
            new RelicLoreDef(RelicId.AlchemistsVial, "Gold in, mercy out.", null, "Fires whenever gold reaches you.", "Distills 1 healing.", null),
            new RelicLoreDef(RelicId.BloodAltar, "It tithes in blood — the enemy's.", null, "Fires whenever you heal.", "Deals 2 damage.", "Its blood also feeds you: heals 1 when it strikes."),
            new RelicLoreDef(RelicId.ThornVest, "Go on, it dares. Hug me.", null, "Fires when you take a hit.", "Deals 2 damage back.", null),
            new RelicLoreDef(RelicId.VampireTooth, "Still hungry after all these years.", null, "Fires on every strike you land.", "Drinks back 1 healing.", "Drains the ceiling: each bite takes 1 max HP from the foe."),
            new RelicLoreDef(RelicId.MidasBlade, "A king's greed, bottled and sold on.", "On pickup: +1 ATK per 50 gold in the purse.", null, "Coughs up 2 gold.", "Recounts live: +1 ATK per 50g at all times."),
            new RelicLoreDef(RelicId.GreedyCurse, "It pays well. It collects better.", "Gold gains doubled; hits hurt +1.", "Fires when you take a hit.", "Scrapes together 2 gold.", "The extra hurt is charged to your purse: 2 gold per point, not HP."),
            new RelicLoreDef(RelicId.SwiftBoots, "They never touch the same stone twice.", "Attack 25% faster.", null, "A burst of pace: +2 SPD this floor.", "Every 4th strike is instant."),
            new RelicLoreDef(RelicId.BattleDash, "The fight starts before they blink.", "You strike first on each floor's opening fight.", null, "A burst of pace: +2 SPD this floor.", "Opens every fight."),
            new RelicLoreDef(RelicId.LuckyClover, "Four leaves. One promise it never states.", "Unlocks evasion: dodge enemy attacks at LCK%. Also +15 LCK.", "Fires when an enemy misses you.", "Releases a luck signal into the chain.", "Dodges release luck signals."),
            new RelicLoreDef(RelicId.IronSkin, "Skin like a rumor — hard to pierce.", "+2 DEF, always.", null, "Hardens: +2 DEF this floor.", "The first hit each fight glances off."),
            new RelicLoreDef(RelicId.AdrenalineGland, "Pain is just ignition.", "First hit each floor: +1 ATK, permanent.", "Fires on the first hit you take each floor.", "+1 ATK this floor.", "Fires on the first hit of every fight."),
            new RelicLoreDef(RelicId.PiggyBank, "Fatter every floor. Never full.", "Cash out for 25% more gold.", null, "Rattles out 1 gold.", null),
            new RelicLoreDef(RelicId.BerserkerCharm, "It only speaks when you bleed.", "+4 ATK while below half HP.", null, "+1 ATK this floor (+2 while bloodied).", "Bloodied: also +25% attack speed."),
            new RelicLoreDef(RelicId.RabbitsFoot, "Unlucky for the rabbit. Lucky for you.", null, "Fires on every luck signal.", "+1 LCK this floor.", "Fires on every signal, even in the arena."),
            new RelicLoreDef(RelicId.CutpurseHook, "It steals mid-swing, and swears it didn't.", "Doubles loose-coin spill odds; spills pay +1 per copy.", "Spills are lucky breaks — luck relics react.", "Nicks 1 gold.", "Every strike spills — no roll."),
            new RelicLoreDef(RelicId.WeightedDice, "Loaded? Prove it.", "Strikes may crit for 1.5× damage (LCK% chance).", "Every crit is a lucky break — luck relics react.", "A 2-damage mini-crit.", "Crits hit ×2."),
            new RelicLoreDef(RelicId.TrollMarrow, "It remembers how to grow back — when it must.", "Bloodied: heal 2 after every hit taken.", null, null, "Knits from the foe: every stitch is drained from their HP."),
            new RelicLoreDef(RelicId.SecondStomach, "Always room for one more meal.", "Breather heals ×2.", null, null, "Breathers also +1 max HP."),
            new RelicLoreDef(RelicId.MartyrsKnot, "Tied once, it gives forever.", "Relic heals +1.", null, null, "Bears it for you: 1 in 3 hits is redirected to the foe entirely."),
            new RelicLoreDef(RelicId.BloodPact, "Sign here. And here. And bleed here.", "-20 HP (versus: -20% max HP per round); +5 ATK forever.", null, null, "The pact pays +8 ATK."),
            new RelicLoreDef(RelicId.GravekeepersSoil, "The ground gave you back. Once.", "Cheat death once per run (25% HP).", null, null, "Rise at 50% HP."),
            new RelicLoreDef(RelicId.PaddedHide, "Soft outside. Softer inside.", "+1 DEF; first hit each fight -2.", null, null, "Learns the blow: after the first hit, that damage lands 50% lighter all fight."),
            new RelicLoreDef(RelicId.MirrorScale, "See how you like it.", null, "Fires when an enemy crits you.", "Reflects the full crit.", "Also reflects normal hits at half."),
            new RelicLoreDef(RelicId.AnvilHeart, "Every blow forges it harder.", "Strikes harden you, blow by blow.", null, null, "The forge never cools: cap +12."),
            new RelicLoreDef(RelicId.SentinelBell, "It rings before the blade arrives.", null, "Fires when you dodge.", "+1 DEF this floor.", "Each ring also chips 1 damage off the foe."),
            new RelicLoreDef(RelicId.FortunesEdge, "Chance, honed to a killing angle.", null, "Fires on luck signals.", "Charges the next strike (+50%).", "Charged strikes hit +100% instead of +50%."),
            new RelicLoreDef(RelicId.QuickenedPulse, "Fortune runs in the veins.", null, "Fires on luck signals.", "+1 SPD this floor.", null),
            new RelicLoreDef(RelicId.DuelistsOath, "Sworn hard. Sworn briefly.", "+4 ATK vs worthy blood; shatters after 4 floors.", null, null, "The oath holds: it never shatters."),
            new RelicLoreDef(RelicId.QuenchedBlade, "Cooled in mercy, swung in anger.", null, "Fires on every 3rd heal.", "+1 ATK this floor.", "Tempers on every heal."),
            new RelicLoreDef(RelicId.ExecutionersCoin, "Heads, it ends. Tails, it ends.", "Execute low foes, once per floor.", null, null, "Executes below 30% HP."),
            new RelicLoreDef(RelicId.WindAnklet, "It hears the arrow leave the string.", "+2 SPD, permanent.", null, null, null),
            new RelicLoreDef(RelicId.Stutterstep, "They swing where you were.", null, "Fires when you dodge.", "Enemy -1 SPD.", "Staggered foes trip: their next strike hits themselves."),
            new RelicLoreDef(RelicId.MomentumBead, "It only rolls downhill.", "Strikes slowly build speed, floor-long.", null, null, "Rolls every 2nd strike."),
            new RelicLoreDef(RelicId.HaresDrum, "Its beat skips when yours should.", null, "Fires when you dodge.", "Instant riposte.", "Ripostes also strike for 2."),
            new RelicLoreDef(RelicId.LoadedHorseshoe, "Nailed on backwards, works anyway.", null, "Fires when you dodge.", "Releases a luck signal.", "+12 LCK per copy."),
            new RelicLoreDef(RelicId.CatsWhisker, "It twitched. Someone paid.", null, "Fires on your first dodge each fight.", "Counter-strike, half ATK.", "Every dodge counters."),
            new RelicLoreDef(RelicId.FortunesDebt, "Luck lends. Luck collects.", "+10 LCK; -10% gold.", null, null, "The debt is forgiven — no gold tax."),
            new RelicLoreDef(RelicId.TollkeepersRing, "Everyone pays at this gate.", null, "Fires on every kill.", "+5 gold.", null),
            new RelicLoreDef(RelicId.MerchantsThumb, "It presses the scale, gently.", "Shop & reroll prices -20%.", null, null, "The bazaar offers TWO deals per visit."),
            new RelicLoreDef(RelicId.GildedPlate, "Wealth, worn close.", "Gold hardens into armor.", null, null, "Gold hardens twice as fast: +1 DEF per 25g."),
            new RelicLoreDef(RelicId.EmberCask, "Violence, distilled and bottled.", null, "Fires when a relic deals damage.", "+1 gold.", null),
            new RelicLoreDef(RelicId.CoinSinger, "Every coin has a voice. It knows the song.", null, "Fires when a relic pays out.", "Emits a luck signal.", "Sings for ALL gold, not just relic gold."),
            new RelicLoreDef(RelicId.HexThread, "Fortune, sharpened to a point.", null, "Fires on luck signals.", "Deals 1.", null),
            new RelicLoreDef(RelicId.HollowIdol, "It counts itself among your treasures.", "Set counts +1; -15 max HP.", null, null, null),
            new RelicLoreDef(RelicId.FamineBell, "When it rings, every table empties.", "No enemy healing; your heals -1.", null, null, "Your heals are exempt from the famine."),
            new RelicLoreDef(RelicId.MillstonePendant, "Strength is just weight you agreed to carry.", "+5 ATK; -5 SPD.", null, null, null),
        };

        public static RelicLoreDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
