// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   8 kinds
// </auto-generated>

namespace RelicRun.Core.Content
{
    /// <summary>The eight relic families. Set bonuses trigger at 3, 5 and 7 of a kind.</summary>
    public enum RelicKind
    {
        Guard = 0,
        Flesh = 1,
        Edge = 2,
        Pace = 3,
        Luck = 4,
        Greed = 5,
        Chain = 6,
        Curse = 7,
    }
}
