// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   names for 50 relics, 19 of them translatable
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>What one relic is called.</summary>
    public sealed class RelicTextDef
    {
        public readonly RelicId Id;

        /// <summary>The shipped English name. Always present.</summary>
        public readonly string Name;

        /// <summary>
        /// The locale key its name lives under, or null when it has none.
        /// </summary>
        /// <remarks>
        /// Thirty-one of the fifty have none: they were added in the source's expansion table,
        /// which is English and was never handed to a translator. A caller asks for the key when
        /// there is one and shows <see cref="Name"/> when there is not.
        /// </remarks>
        public readonly string NameKey;

        public RelicTextDef(RelicId id, string name, string nameKey)
        {
            Id = id;
            Name = name;
            NameKey = nameKey;
        }

        /// <summary>Whether this relic's name reaches a delver in their own language.</summary>
        public bool Translated { get { return NameKey != null; } }
    }

    /// <summary>
    /// The relic names, and which of them a translator has seen.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules. Nothing in the engine reads this; the combat log and the relic
    /// book do.
    /// </remarks>
    public static class RelicText
    {
        public static readonly IReadOnlyList<RelicTextDef> All = new[]
        {
            new RelicTextDef(RelicId.Whetstone, "Whetstone", "it_whetstone_n"),
            new RelicTextDef(RelicId.OxHeart, "Ox Heart", "it_heart_n"),
            new RelicTextDef(RelicId.DebtOfFlesh, "Debt of Flesh", null),
            new RelicTextDef(RelicId.CoinMagnet, "Coin Magnet", "it_magnet_n"),
            new RelicTextDef(RelicId.AlchemistsVial, "Alchemist's Vial", "it_alchemist_n"),
            new RelicTextDef(RelicId.BloodAltar, "Blood Altar", "it_altar_n"),
            new RelicTextDef(RelicId.ThornVest, "Thorn Vest", "it_thorns_n"),
            new RelicTextDef(RelicId.VampireTooth, "Vampire Tooth", "it_tooth_n"),
            new RelicTextDef(RelicId.MidasBlade, "Midas Blade", "it_midas_n"),
            new RelicTextDef(RelicId.GreedyCurse, "Greedy Curse", "it_greed_n"),
            new RelicTextDef(RelicId.SwiftBoots, "Swift Boots", "it_boots_n"),
            new RelicTextDef(RelicId.BattleDash, "Battle Dash", "it_dash_n"),
            new RelicTextDef(RelicId.LuckyClover, "Lucky Clover", "it_clover_n"),
            new RelicTextDef(RelicId.IronSkin, "Iron Skin", "it_iron_n"),
            new RelicTextDef(RelicId.AdrenalineGland, "Adrenaline Gland", "it_adrenaline_n"),
            new RelicTextDef(RelicId.PiggyBank, "Piggy Bank", "it_piggy_n"),
            new RelicTextDef(RelicId.BerserkerCharm, "Berserker Charm", "it_berserk_n"),
            new RelicTextDef(RelicId.RabbitsFoot, "Rabbit’s Foot", "it_rabbit_n"),
            new RelicTextDef(RelicId.CutpurseHook, "Cutpurse Hook", "it_cutpurse_n"),
            new RelicTextDef(RelicId.WeightedDice, "Weighted Dice", "it_dice_n"),
            new RelicTextDef(RelicId.TrollMarrow, "Troll Marrow", null),
            new RelicTextDef(RelicId.SecondStomach, "Second Stomach", null),
            new RelicTextDef(RelicId.MartyrsKnot, "Martyr's Knot", null),
            new RelicTextDef(RelicId.BloodPact, "Blood Pact", null),
            new RelicTextDef(RelicId.GravekeepersSoil, "Gravekeeper's Soil", null),
            new RelicTextDef(RelicId.PaddedHide, "Padded Hide", null),
            new RelicTextDef(RelicId.MirrorScale, "Mirror Scale", null),
            new RelicTextDef(RelicId.AnvilHeart, "Anvil Heart", null),
            new RelicTextDef(RelicId.SentinelBell, "Sentinel Bell", null),
            new RelicTextDef(RelicId.FortunesEdge, "Fortune's Edge", null),
            new RelicTextDef(RelicId.QuickenedPulse, "Quickened Pulse", null),
            new RelicTextDef(RelicId.DuelistsOath, "Duelist's Oath", null),
            new RelicTextDef(RelicId.QuenchedBlade, "Quenched Blade", null),
            new RelicTextDef(RelicId.ExecutionersCoin, "Executioner's Coin", null),
            new RelicTextDef(RelicId.WindAnklet, "Wind Anklet", null),
            new RelicTextDef(RelicId.Stutterstep, "Stutterstep", null),
            new RelicTextDef(RelicId.MomentumBead, "Momentum Bead", null),
            new RelicTextDef(RelicId.HaresDrum, "Hare's Drum", null),
            new RelicTextDef(RelicId.LoadedHorseshoe, "Loaded Horseshoe", null),
            new RelicTextDef(RelicId.CatsWhisker, "Cat's Whisker", null),
            new RelicTextDef(RelicId.FortunesDebt, "Fortune's Debt", null),
            new RelicTextDef(RelicId.TollkeepersRing, "Tollkeeper's Ring", null),
            new RelicTextDef(RelicId.MerchantsThumb, "Merchant's Thumb", null),
            new RelicTextDef(RelicId.GildedPlate, "Gilded Plate", null),
            new RelicTextDef(RelicId.EmberCask, "Ember Cask", null),
            new RelicTextDef(RelicId.CoinSinger, "Coin Singer", null),
            new RelicTextDef(RelicId.HexThread, "Hex Thread", null),
            new RelicTextDef(RelicId.HollowIdol, "Hollow Idol", null),
            new RelicTextDef(RelicId.FamineBell, "Famine Bell", null),
            new RelicTextDef(RelicId.MillstonePendant, "Millstone Pendant", null),
        };

        public static RelicTextDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
