// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   8 relic families, 22 tiers, English only
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One step of a set bonus: how many of a kind, and what that buys.</summary>
    public sealed class SetTier
    {
        /// <summary>How many relics of the kind are needed.</summary>
        public readonly int Needs;

        /// <summary>What it does, in English.</summary>
        public readonly string What;

        public SetTier(int needs, string what)
        {
            Needs = needs;
            What = what;
        }
    }

    /// <summary>One relic family and what collecting it is worth.</summary>
    public sealed class SetDef
    {
        public readonly RelicKind Kind;

        /// <summary>The name the game prints, upper case, as the source writes it.</summary>
        public readonly string Name;

        /// <summary>The family's colour, as <c>#RRGGBB</c>. Read with <see cref="Rgb.Parse"/>.</summary>
        public readonly string Hex;

        /// <summary>Its steps, in ascending order of how many are needed.</summary>
        public readonly IReadOnlyList<SetTier> Tiers;

        public SetDef(RelicKind kind, string name, string hex, IReadOnlyList<SetTier> tiers)
        {
            Kind = kind;
            Name = name;
            Hex = hex;
            Tiers = tiers;
        }
    }

    /// <summary>The eight relic families.</summary>
    public static class SetCatalog
    {
        public static readonly IReadOnlyList<SetDef> All = new[]
        {
            new SetDef(RelicKind.Guard, "GUARD", "#7A93A8", new[] { new SetTier(3, "+3 DEF"), new SetTier(5, "Thorns strike +1"), new SetTier(7, "First blow each fight glances off") }),
            new SetDef(RelicKind.Flesh, "FLESH", "#C4595C", new[] { new SetTier(3, "+3 max HP"), new SetTier(5, "All heals +1"), new SetTier(7, "Once per floor: refuse death at 1 HP") }),
            new SetDef(RelicKind.Edge, "EDGE", "#D08B4C", new[] { new SetTier(3, "+1 ATK"), new SetTier(5, "Every 4th strike ×1.5"), new SetTier(7, "+1 permanent ATK per kill") }),
            new SetDef(RelicKind.Pace, "PACE", "#5FB3C9", new[] { new SetTier(3, "+2 SPD"), new SetTier(5, "Attack gauge starts 25% filled"), new SetTier(7, "Every 5th strike hits twice") }),
            new SetDef(RelicKind.Luck, "LUCK", "#9B8BD0", new[] { new SetTier(3, "+5 LCK"), new SetTier(5, "Crits emit a luck signal"), new SetTier(7, "Dodges counter for 2") }),
            new SetDef(RelicKind.Greed, "GREED", "#E3B341", new[] { new SetTier(3, "Gold ×1.15"), new SetTier(5, "Cutpurse spills +1"), new SetTier(7, "Kill loot ×1.5") }),
            new SetDef(RelicKind.Chain, "CHAIN", "#B77BC4", new[] { new SetTier(3, "Chain decay softens"), new SetTier(5, "Chain cap +1"), new SetTier(7, "Chain decay barely bites (×0.75)") }),
            new SetDef(RelicKind.Curse, "CURSE", "#8BA65B", new[] { new SetTier(3, "+1 ATK") }),
        };

        public static SetDef Get(RelicKind kind)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Kind == kind) return All[i];
            }

            return null;
        }
    }
}
