// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   8 triggers, 7 emitters
// </auto-generated>

namespace RelicRun.Core.Content
{
    /// <summary>
    /// What fires a socketed relic. Bought at the bazaar and attached to ONE COPY of a relic,
    /// which is why sockets are keyed by inventory index rather than by relic id.
    /// </summary>
    public enum SocketTrigger
    {
        None = 0,
        Attack = 1,
        Hit = 2,
        Gold = 3,
        Kill = 4,
        Dodge = 5,
        Luck = 6,
        Floor = 7,
        Fight = 8,
    }

    /// <summary>What a socketed relic additionally does when it activates.</summary>
    public enum SocketEmitter
    {
        None = 0,
        Dmg = 1,
        Heal = 2,
        Gold = 3,
        Atk = 4,
        Def = 5,
        Spd = 6,
        Luck = 7,
    }
}
