// <auto-generated>
//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.
//   Do not edit by hand — re-run the generator instead.
//   8 triggers, 7 emitters, English only
// </auto-generated>

using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>What one socket is called, and what it does when it is fitted.</summary>
    public sealed class SocketTextDef
    {
        /// <summary>The source game's id, e.g. "t_kill".</summary>
        public readonly string Key;

        public readonly string Name;

        /// <summary>What fitting it changes, in English.</summary>
        public readonly string What;

        public SocketTextDef(string key, string name, string what)
        {
            Key = key;
            Name = name;
            What = what;
        }
    }

    /// <summary>The socket catalogue, as far as reading it is concerned.</summary>
    public static class SocketText
    {
        /// <summary>Indexed by <see cref="SocketTrigger"/>, so slot zero is None and is null.</summary>
        public static readonly IReadOnlyList<SocketTextDef> Triggers = new[]
        {
            null,
            new SocketTextDef("t_attack", "Attack Trigger", "Socketed relic also activates on every 3rd strike each floor."),
            new SocketTextDef("t_hit", "Pain Trigger", "Socketed relic also activates on every 3rd hit you take each floor."),
            new SocketTextDef("t_gold", "Gold Trigger", "Socketed relic also activates on every 3rd gold gain each floor."),
            new SocketTextDef("t_kill", "Kill Trigger", "Socketed relic also activates on every kill."),
            new SocketTextDef("t_dodge", "Dodge Trigger", "Socketed relic also activates when an enemy misses you."),
            new SocketTextDef("t_luck", "Luck Trigger", "Socketed relic also activates on a lucky break (luck events)."),
            new SocketTextDef("t_floor", "Floor Trigger", "Socketed relic also activates as each floor's first fight begins."),
            new SocketTextDef("t_fight", "Fight Trigger", "Socketed relic also activates as each fight begins."),
        };

        /// <summary>Indexed by <see cref="SocketEmitter"/>, so slot zero is None and is null.</summary>
        public static readonly IReadOnlyList<SocketTextDef> Emitters = new[]
        {
            null,
            new SocketTextDef("e_dmg", "Fang Emitter", "When the socketed relic activates: deal 2 damage."),
            new SocketTextDef("e_heal", "Salve Emitter", "When the socketed relic activates: heal 1."),
            new SocketTextDef("e_gold", "Coin Emitter", "When the socketed relic activates: gain 2 gold."),
            new SocketTextDef("e_atk", "Fury Emitter", "When the socketed relic activates: +1 attack this floor."),
            new SocketTextDef("e_def", "Stone Emitter", "When the socketed relic activates: +1 defense this floor."),
            new SocketTextDef("e_spd", "Gale Emitter", "When the socketed relic activates: +1 speed this floor."),
            new SocketTextDef("e_luck", "Charm Emitter", "When the socketed relic activates: +1 luck this floor."),
        };

        /// <summary>What a trigger says, or null for <see cref="SocketTrigger.None"/>.</summary>
        public static SocketTextDef Of(SocketTrigger trigger)
        {
            var at = (int)trigger;
            return at >= 0 && at < Triggers.Count ? Triggers[at] : null;
        }

        /// <summary>What an emitter says, or null for <see cref="SocketEmitter.None"/>.</summary>
        public static SocketTextDef Of(SocketEmitter emitter)
        {
            var at = (int)emitter;
            return at >= 0 && at < Emitters.Count ? Emitters[at] : null;
        }
    }
}
