/*
 * Relic Run content extractor
 * ---------------------------
 * Parses .port/Daily Delve.dc.html and .port/strings.js and emits the game's
 * content tables as JSON into Tools/out/, ready for the Unity ScriptableObject
 * importer (Phase 8 of docs/port-plan.md).
 *
 * The source data lives in plain JS object literals, so we brace-match each
 * declaration and evaluate it in a sandboxed vm rather than regexing it. A few
 * tables carry closures (event outcomes, achievement predicates); those are
 * serialized as { __fn: "<source>" } so the port has the exact logic to read,
 * and are flagged in the manifest as needing a hand-written C# counterpart.
 *
 * Re-runnable: delete Tools/out and run `node Tools/extract/extract.mjs`.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const PORT = join(ROOT, ".port");
const OUT = join(ROOT, "Tools", "out");
const SRC = readFileSync(join(PORT, "Daily Delve.dc.html"), "utf8");
const STRINGS_SRC = readFileSync(join(PORT, "strings.js"), "utf8");

/* ---------- helpers ---------- */

const warnings = [];
const warn = (m) => { warnings.push(m); console.warn("  ! " + m); };

/** Brace/bracket-match a top-level `const NAME = <literal>` and return its source text. */
function literalOf(name) {
  const decl = new RegExp(`\\bconst ${name}\\s*=\\s*`).exec(SRC);
  if (!decl) throw new Error(`declaration not found: ${name}`);
  let i = decl.index + decl[0].length;
  const open = SRC[i];
  const close = open === "{" ? "}" : open === "[" ? "]" : null;
  if (!close) throw new Error(`${name} is not an object/array literal`);
  let depth = 0, inStr = null, esc = false;
  for (let k = i; k < SRC.length; k++) {
    const c = SRC[k];
    if (esc) { esc = false; continue; }
    if (inStr) {
      if (c === "\\") esc = true;
      else if (c === inStr) inStr = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") { inStr = c; continue; }
    if (c === "/" && SRC[k + 1] === "*") { k = SRC.indexOf("*/", k + 2) + 1; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return SRC.slice(i, k + 1); }
  }
  throw new Error(`unterminated literal: ${name}`);
}

/** Evaluate a literal in a sandbox. Free identifiers inside closures are fine —
 *  the closures are never invoked, only stringified. */
function evalLiteral(name) {
  const ctx = vm.createContext({ Math, Object, Store: { get: () => 0, set: () => {} } });
  return vm.runInContext(`(${literalOf(name)})`, ctx, { filename: `${name}.js` });
}

/** Scalar `const NAME = 123` (supports comma-chained declarations). */
function scalars(...names) {
  const out = {};
  for (const n of names) {
    const m = new RegExp(`\\b${n}\\s*=\\s*(-?[0-9.]+)`).exec(SRC);
    if (!m) { warn(`scalar not found: ${n}`); continue; }
    out[n] = Number(m[1]);
  }
  return out;
}

/** Serialize, turning functions into { __fn } so closure logic survives to the port. */
const fnAware = (_k, v) =>
  typeof v === "function" ? { __fn: v.toString().replace(/\s+/g, " ").trim() } : v;

function write(rel, data) {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(data, fnAware, 2) + "\n", "utf8");
  const n = Array.isArray(data) ? data.length : Object.keys(data).length;
  console.log(`  → ${rel} (${n} entries)`);
}

/** docs/relics-cut.md — the triage record required by Phase 0 of the port plan. */
function writeCutDoc(cut) {
  const rows = cut.map((r) =>
    `### ${r.n}  \`${r.id}\`\n\n` +
    `> ${r.fl || ""}\n\n` +
    `**Card text.** ${r.d}\n\n` +
    (r.pas ? `**Passive.** ${r.pas}\n\n` : "") +
    (r.nat ? `**Native trigger.** ${r.nat}\n\n` : "") +
    (r.act ? `**On activation.** ${r.act}\n\n` : "") +
    `**Live references** — combat engine: ${r.engineRefs} · stat ledger: ${r.ledgerRefs} · whole file: ${r.totalRefs}\n`
  ).join("\n---\n\n");
  const inEngine = cut.filter((r) => r.engineRefs > 0).length;
  const inLedger = cut.filter((r) => r.engineRefs === 0 && r.ledgerRefs > 0).length;
  const elsewhere = cut.filter((r) => r.engineRefs === 0 && r.ledgerRefs === 0 && r.totalRefs > 1).length;

  const doc =
`# Cut relics — triage record

Generated by \`Tools/extract/extract.mjs\`. Do not edit by hand.

These **${cut.length}** relics have finished card text in \`NEWR\` and live code paths behind them
— ${inEngine} in the combat engine, ${inLedger} in the stat ledger, ${elsewhere} in run/UI code — but they are
**absent from \`ITEMS\`**, the table that defines the draft pool. Nothing can ever offer
them, so no player has ever held one and none has been playtested.

Per the locked decision in [port-plan.md](port-plan.md), they are **cut from the port**:
the 50 reachable relics ship, and these are recorded here so any of them can be
reintroduced deliberately rather than by accident.

**To reintroduce one:** add an \`ITEMS\` entry (kind, emits/reacts, modes, stack), assign a
cell in \`assets/relic-icons.png\`, add its text to all 8 locales, then port its effect. It
is new content that needs balancing, not a restoration.

---

${rows}
`;
  const p = join(ROOT, "docs", "relics-cut.md");
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, doc, "utf8");
  console.log(`  → docs/relics-cut.md (${cut.length} relics)`);
}

/* ---------- 1. locales ---------- */

console.log("\nlocales");
const strCtx = vm.createContext({ window: {} });
vm.runInContext(STRINGS_SRC, strCtx, { filename: "strings.js" });
const LOCALES = strCtx.window.DD_STRINGS;
const LOCALE_IDS = Object.keys(LOCALES);
for (const id of LOCALE_IDS) write(`locales/${id}.json`, LOCALES[id]);

/* ---------- 2. relics ---------- */

console.log("\nrelics");
const ITEMS = evalLiteral("ITEMS");
const NEWR = evalLiteral("NEWR");
const RELIC_ICON = evalLiteral("RELIC_ICON");
const NATIVE_TRIGGER = evalLiteral("NATIVE_TRIGGER"); // dead in JS, but real design intent
const EN = LOCALES.en;

const relicText = (id) => {
  const fromStrings = EN[`it_${id}_n`] != null;
  if (fromStrings) return { name: EN[`it_${id}_n`], desc: EN[`it_${id}_d`], source: "strings" };
  const n = NEWR[id];
  if (!n) { warn(`no text for relic ${id}`); return { name: id, desc: "", source: "missing" }; }
  return { name: n.n, desc: n.d, flavor: n.fl, passive: n.pas, nativeText: n.nat, activeText: n.act, source: "NEWR" };
};

const relics = Object.entries(ITEMS).map(([id, it]) => ({
  id,
  kind: it.kind,
  glyph: it.g,
  stackable: !!it.stack,
  modes: it.modes || ["delve", "versus"],
  emits: it.emits || [],
  reacts: it.reacts || [],
  wheel: it.wheel || null,
  nativeTrigger: NATIVE_TRIGGER[id] || null,
  icon: RELIC_ICON[id] ? { col: RELIC_ICON[id][0], row: RELIC_ICON[id][1] } : null,
  text: relicText(id),
}));
for (const r of relics) if (!r.icon) warn(`relic ${r.id} has no icon cell`);
write("relics.json", relics);

/* the ones the engine implements but ITEMS never exposes — cut, but recorded.
   We check each against the engine source so the triage doc states, per relic,
   whether live code paths exist for it (they all do, today). */
const ENGINE = SRC.slice(SRC.indexOf("  simulateFloor(st, pack, rng)"), SRC.indexOf("  lineFor(e)"));
const LEDGER = SRC.slice(SRC.indexOf("function heroStatRows(ctx, stat)"), SRC.indexOf("function heroCtxOf(st, foeRank)"));
const refs = (hay, id) => (hay.match(new RegExp(`"${id}"`, "g")) || []).length;
const cut = Object.keys(NEWR)
  .filter((id) => !(id in ITEMS))
  .map((id) => ({
    id,
    ...NEWR[id],
    engineRefs: refs(ENGINE, id),
    ledgerRefs: refs(LEDGER, id),
    totalRefs: refs(SRC, id),
  }));
write("relics-cut.json", cut);
writeCutDoc(cut);

/* ---------- 3. kinds & sockets ---------- */

console.log("\nkinds & sockets");
write("kinds.json", evalLiteral("KIND_META"));
/* The engine's trigger BUS is wider than the socket catalogue: fireTrig() is called with
   channels that no purchasable TRIGGER exposes, so those calls can never match a socket.
   Derive both sets from the source so the asymmetry is visible instead of assumed. */
const busTriggers = [...new Set(
  [...SRC.matchAll(/fireTrig\("(t_[a-z]+)"/g)].map((m) => m[1])
)].sort();
const TRIGGERS = evalLiteral("TRIGGERS");
write("sockets.json", {
  triggers: TRIGGERS,
  emitters: evalLiteral("EMITTERS"),
  busTriggers,
  unsocketableBusTriggers: busTriggers.filter((t) => !(t in TRIGGERS)),
});

/* ---------- 4. dungeons ---------- */

console.log("\ndungeons");
write("dungeons.json", evalLiteral("DUNGEONS"));

/* ---------- 4b. the palette ---------- */

/* A hero's pixels are ROLE KEYS rather than colours — one letter meaning "hair", or "the dark
   side of the outfit" — and a palette turns keys into colours at draw time. That is what lets
   the Changing Room recolour a delver without touching a sprite, so the table of families is
   content in exactly the way the relic table is. */

console.log("\npalette");
write("palette.json", {
  families: evalLiteral("FAMILIES"),
  solos: evalLiteral("SOLOS"),
  shade: evalLiteral("SHADE_DEFAULTS"),
});

/* ---------- 4c. the hero rig ---------- */

/* The registry a hero pack is drawn against: the canvas, the wardrobe slots, the animation
   states and what every role key means. A pack declares its own states so it can be validated
   against them, but the REGISTRY is what decides how long a state runs and how many frames it
   has — a distinction that is easy to miss and changes every animation if you get it wrong. */

console.log("\nhero rig");
const packLit = evalLiteral("PACK");
write("hero.json", {
  defaultSize: 32,
  slots: packLit.SLOTS,
  states: packLit.STATES,
  roles: packLit.ROLES,
});


/* ---------- 5. enemies ---------- */

console.log("\nenemies");
const ENEMY_G = evalLiteral("ENEMY_G");
const ENEMY_ROW = evalLiteral("ENEMY_ROW");
const ladderM = /const LADDER = (\[[^\]]*\]);/.exec(SRC);
const spareM = /const SPARE = (\d+)/.exec(SRC);
if (!ladderM) warn("LADDER not found in packFor");
write("enemies.json", {
  species: ENEMY_G.map((name, idx) => ({ idx, id: name, sheetRow: ENEMY_ROW[idx] })),
  sheet: { file: "assets/enemies-hoard.png", cols: 3, rows: 13, cell: 64, columnIsRank: ["guard", "elite", "boss"] },
  ladder: ladderM ? JSON.parse(ladderM[1]) : null,
  spare: spareM ? Number(spareM[1]) : null,
  kingSpecies: 9,
  notes: "Column = rank variant, row = species. LADDER is floor-order; SPARE is the king's honour guard.",
});

/* ---------- 6. events ---------- */

console.log("\nevents");
const EVENTS = evalLiteral("EVENTS");
write("events.json", EVENTS.map((e, i) => ({
  index: i, cat: e.cat, title: e.title, art: e.art, text: e.text,
  choices: (e.choices || []).map((c) => ({
    label: c.label, hint: c.hint || null, cost: c.cost || null, run: c.run,
  })),
})));

/* ---------- 7. progression & constants ---------- */

console.log("\nprogression & constants");
const META = evalLiteral("META");
write("progression.json", {
  structuralPerks: META.STRUCT,
  xpSteps: META.XP_STEPS,
  xpFloor: META.XP_FLOOR,
  needFormula: META.need,
  bonusesFormula: META.bonuses,
  tierMult: META.tierMult,
  achievements: META.ACHV,
});
write("constants.json", {
  ...scalars("MAX_FLOOR", "CHAIN_CAP", "SUPPORTER_SPARKS", "REVIVE_SPARKS",
             "SHOP_FLOOR", "SHOP_BUY", "SHOP_UP", "EV_MIN_SPD", "EV_MIN_DEF",
             "SHEET_COLS", "SHEET_ROWS", "SHEET_CELL"),
  hallAspect: [650, 181],
  defenseK: 20,
  merchantLines: evalLiteral("MERCHANT_LINES"),
});

/* ---------- manifest ---------- */

const manifest = {
  generated: new Date().toISOString(),
  source: "Daily Delve.dc.html",
  counts: {
    relics: relics.length,
    relicsCut: cut.length,
    kinds: Object.keys(evalLiteral("KIND_META")).length,
    dungeons: evalLiteral("DUNGEONS").length,
    colourFamilies: evalLiteral("FAMILIES").length,
    events: EVENTS.length,
    species: ENEMY_G.length,
    triggers: Object.keys(evalLiteral("TRIGGERS")).length,
    emitters: Object.keys(evalLiteral("EMITTERS")).length,
    locales: LOCALE_IDS.length,
  },
  localeIds: LOCALE_IDS,
  needsHandPort: [
    "events.json → choices[].run: outcome closures, port to C# EventOutcome handlers",
    "progression.json → needFormula / bonusesFormula / tierMult: port to Progression.cs",
    "progression.json → achievements[].ok: predicates read save state, port to C#",
  ],
  warnings,
};
write("manifest.json", manifest);

console.log(`\ndone — ${warnings.length} warning(s)\n`);
