/*
 * Relic Run content extractor
 * ---------------------------
 * Parses .port/Daily Delve.dc.html and .port/strings.js and emits the game's
 * content tables as JSON into Tools/out/, ready for the Unity ScriptableObject
 * importer (Phase 8 of docs/port-plan.md).
 *
 * The source data lives in plain JS object literals, so we brace-match each
 * declaration and evaluate it in a sandboxed vm rather than regexing it. A few
 * tables carry closures (event outcomes, achievement predicates); those are
 * serialized as { __fn: "<source>" } so the port has the exact logic to read,
 * and are flagged in the manifest as needing a hand-written C# counterpart.
 *
 * Re-runnable: delete Tools/out and run `node Tools/extract/extract.mjs`.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const PORT = join(ROOT, ".port");
const OUT = join(ROOT, "Tools", "out");
const SRC = readFileSync(join(PORT, "Daily Delve.dc.html"), "utf8");
const STRINGS_SRC = readFileSync(join(PORT, "strings.js"), "utf8");

/* ---------- helpers ---------- */

const warnings = [];
const warn = (m) => { warnings.push(m); console.warn("  ! " + m); };

/** Brace/bracket-match a top-level `const NAME = <literal>` and return its source text. */
function literalOf(name) {
  const decl = new RegExp(`\\bconst ${name}\\s*=\\s*`).exec(SRC);
  if (!decl) throw new Error(`declaration not found: ${name}`);
  let i = decl.index + decl[0].length;
  const open = SRC[i];
  const close = open === "{" ? "}" : open === "[" ? "]" : null;
  if (!close) throw new Error(`${name} is not an object/array literal`);
  let depth = 0, inStr = null, esc = false;
  for (let k = i; k < SRC.length; k++) {
    const c = SRC[k];
    if (esc) { esc = false; continue; }
    if (inStr) {
      if (c === "\\") esc = true;
      else if (c === inStr) inStr = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") { inStr = c; continue; }
    if (c === "/" && SRC[k + 1] === "*") { k = SRC.indexOf("*/", k + 2) + 1; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return SRC.slice(i, k + 1); }
  }
  throw new Error(`unterminated literal: ${name}`);
}

/** Evaluate a literal in a sandbox. Free identifiers inside closures are fine —
 *  the closures are never invoked, only stringified. */
function evalLiteral(name) {
  const ctx = vm.createContext({ Math, Object, Store: { get: () => 0, set: () => {} } });
  return vm.runInContext(`(${literalOf(name)})`, ctx, { filename: `${name}.js` });
}

/** Scalar `const NAME = 123` (supports comma-chained declarations). */
function scalars(...names) {
  const out = {};
  for (const n of names) {
    const m = new RegExp(`\\b${n}\\s*=\\s*(-?[0-9.]+)`).exec(SRC);
    if (!m) { warn(`scalar not found: ${n}`); continue; }
    out[n] = Number(m[1]);
  }
  return out;
}

/** Serialize, turning functions into { __fn } so closure logic survives to the port. */
const fnAware = (_k, v) =>
  typeof v === "function" ? { __fn: v.toString().replace(/\s+/g, " ").trim() } : v;

function write(rel, data) {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(data, fnAware, 2) + "\n", "utf8");
  const n = Array.isArray(data) ? data.length : Object.keys(data).length;
  console.log(`  → ${rel} (${n} entries)`);
}

/** docs/relics-cut.md — the triage record required by Phase 0 of the port plan. */
function writeCutDoc(cut) {
  const rows = cut.map((r) =>
    `### ${r.n}  \`${r.id}\`\n\n` +
    `> ${r.fl || ""}\n\n` +
    `**Card text.** ${r.d}\n\n` +
    (r.pas ? `**Passive.** ${r.pas}\n\n` : "") +
    (r.nat ? `**Native trigger.** ${r.nat}\n\n` : "") +
    (r.act ? `**On activation.** ${r.act}\n\n` : "") +
    `**Live references** — combat engine: ${r.engineRefs} · stat ledger: ${r.ledgerRefs} · whole file: ${r.totalRefs}\n`
  ).join("\n---\n\n");
  const inEngine = cut.filter((r) => r.engineRefs > 0).length;
  const inLedger = cut.filter((r) => r.engineRefs === 0 && r.ledgerRefs > 0).length;
  const elsewhere = cut.filter((r) => r.engineRefs === 0 && r.ledgerRefs === 0 && r.totalRefs > 1).length;

  const doc =
`# Cut relics — triage record

Generated by \`Tools/extract/extract.mjs\`. Do not edit by hand.

These **${cut.length}** relics have finished card text in \`NEWR\` and live code paths behind them
— ${inEngine} in the combat engine, ${inLedger} in the stat ledger, ${elsewhere} in run/UI code — but they are
**absent from \`ITEMS\`**, the table that defines the draft pool. Nothing can ever offer
them, so no player has ever held one and none has been playtested.

Per the locked decision in [port-plan.md](port-plan.md), they are **cut from the port**:
the 50 reachable relics ship, and these are recorded here so any of them can be
reintroduced deliberately rather than by accident.

**To reintroduce one:** add an \`ITEMS\` entry (kind, emits/reacts, modes, stack), assign a
cell in \`assets/relic-icons.png\`, add its text to all 8 locales, then port its effect. It
is new content that needs balancing, not a restoration.

---

${rows}
`;
  const p = join(ROOT, "docs", "relics-cut.md");
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, doc, "utf8");
  console.log(`  → docs/relics-cut.md (${cut.length} relics)`);
}

/* ---------- 1. locales ---------- */

console.log("\nlocales");
const strCtx = vm.createContext({ window: {} });
vm.runInContext(STRINGS_SRC, strCtx, { filename: "strings.js" });
const LOCALES = strCtx.window.DD_STRINGS;
const LOCALE_IDS = Object.keys(LOCALES);

/*
 * Strings the PORT adds, in every language the source ships.
 *
 * The source writes a handful of its labels straight into the markup rather than
 * through DD_STRINGS, so they are English on a Japanese screen. Where the port
 * draws one of those, it needs a key — and a key with nothing behind it shows as
 * the key, which is worse than English.
 *
 * Everything here is therefore OURS, not the source's, and is marked as such: a
 * later extraction must not quietly turn one of these into a translation nobody
 * wrote. English is the fallback for any language left out.
 */
const ADDED = {
  /* The draft's reroll button. The source's markup reads "↻ REROLL" and then
   * "— {n} GOLD" on a second line; the arrow is stripped by Locale.Clean the way
   * every other icon in this table is, so it is not written here. */
  reroll: {
    en: "REROLL \u2014 {n} GOLD",
    tr: "YEN\u0130DEN \u00C7EK \u2014 {n} ALTIN",
    fr: "RELANCER \u2014 {n} OR",
    es: "RELANZAR \u2014 {n} ORO",
    ru: "\u041F\u0415\u0420\u0415\u0411\u0420\u041E\u0421 \u2014 {n} \u0417\u041E\u041B\u041E\u0422\u0410",
    ja: "\u5F15\u304D\u76F4\u3057 \u2014 {n} \u30B4\u30FC\u30EB\u30C9",
    zh: "\u91CD\u65B0\u62BD\u53D6 \u2014 {n} \u91D1\u5E01",
    ar: "\u0625\u0639\u0627\u062F\u0629 \u0627\u0644\u0633\u062D\u0628 \u2014 {n} \u0630\u0647\u0628",
  },

  /* Under the numbers on the card a fight opens on. The source writes this one in
   * English into its markup too, and it is the only sentence on that screen — the
   * rest is a name and five numbers — so leaving it untranslated would leave the
   * one readable line of the game's biggest moment in the wrong language. */
  blocksWay: {
    en: "It blocks the way.",
    tr: "Yolu kap\u0131yor.",
    fr: "Il barre le passage.",
    es: "Bloquea el camino.",
    ru: "\u041E\u043D\u043E \u043F\u0440\u0435\u0433\u0440\u0430\u0436\u0434\u0430\u0435\u0442 \u043F\u0443\u0442\u044C.",
    ja: "\u884C\u304F\u624B\u3092\u962E\u3093\u3067\u3044\u308B\u3002",
    zh: "\u5B83\u6321\u4F4F\u4E86\u53BB\u8DEF\u3002",
    ar: "\u064A\u0633\u062F\u0651 \u0627\u0644\u0637\u0631\u064A\u0642.",
  },

  /* The kicker over the gate. The source writes "FLOOR n CLEARED" into its
   * markup. */
  floorCleared: {
    en: "FLOOR {n} CLEARED",
    tr: "KAT {n} TEM\u0130ZLEND\u0130",
    fr: "\u00C9TAGE {n} NETTOY\u00C9",
    es: "PISO {n} DESPEJADO",
    ru: "\u042D\u0422\u0410\u0416 {n} \u0417\u0410\u0427\u0418\u0429\u0415\u041D",
    ja: "{n}\u968E \u30AF\u30EA\u30A2",
    zh: "\u7B2C {n} \u5C42 \u5DF2\u6E05\u7A7A",
    ar: "\u062A\u0645 \u062A\u0637\u0647\u064A\u0631 \u0627\u0644\u0637\u0627\u0628\u0642 {n}",
  },

  /* The gate's title. Two short lines in the source, and the whole mood of the
   * screen a delver decides on. */
  stairsDown: {
    en: "The stairs go down.",
    tr: "Merdivenler a\u015Fa\u011F\u0131 iniyor.",
    fr: "L'escalier descend.",
    es: "La escalera baja.",
    ru: "\u041B\u0435\u0441\u0442\u043D\u0438\u0446\u0430 \u0432\u0435\u0434\u0451\u0442 \u0432\u043D\u0438\u0437.",
    ja: "\u968E\u6BB5\u306F\u4E0B\u3078\u7D9A\u3044\u3066\u3044\u308B\u3002",
    zh: "\u697C\u68AF\u901A\u5411\u4E0B\u65B9\u3002",
    ar: "\u0627\u0644\u062F\u0631\u062C \u064A\u0647\u0628\u0637 \u0625\u0644\u0649 \u0627\u0644\u0623\u0633\u0641\u0644.",
  },

  /* Under the gold on the gate. */
  inThePurse: {
    en: "IN THE PURSE",
    tr: "KESEDE",
    fr: "DANS LA BOURSE",
    es: "EN LA BOLSA",
    ru: "\u0412 \u041A\u041E\u0428\u0415\u041B\u042C\u041A\u0415",
    ja: "\u8CA1\u5E03\u306E\u4E2D",
    zh: "\u94B1\u888B\u91CC",
    ar: "\u0641\u064A \u0627\u0644\u0643\u064A\u0633",
  },

  /* Over the descend button. */
  riskItAll: {
    en: "RISK IT ALL",
    tr: "HEPS\u0130N\u0130 R\u0130SKE AT",
    fr: "TOUT RISQUER",
    es: "ARRI\u00C9SGALO TODO",
    ru: "\u0420\u0418\u0421\u041A\u041D\u0423\u0422\u042C \u0412\u0421\u0415\u041C",
    ja: "\u3059\u3079\u3066\u8CED\u3051\u308B",
    zh: "\u5B64\u6CE8\u4E00\u63B7",
    ar: "\u062E\u0627\u0637\u0631 \u0628\u0643\u0644 \u0634\u064A\u0621",
  },

  /* And under it, what the bet costs if it is lost. */
  riskGold: {
    en: "RISK {n}",
    tr: "R\u0130SK {n}",
    fr: "RISQUE {n}",
    es: "ARRIESGA {n}",
    ru: "\u0421\u0422\u0410\u0412\u041A\u0410 {n}",
    ja: "\u8CED\u3051 {n}",
    zh: "\u8D4C\u4E0A {n}",
    ar: "\u062A\u062E\u0627\u0637\u0631 \u0628\u0640 {n}",
  },

  /* Over the cash-out button. */
  walkAway: {
    en: "WALK AWAY",
    tr: "\u00C7EK\u0130L G\u0130T",
    fr: "S'EN ALLER",
    es: "MARCHARSE",
    ru: "\u0423\u0419\u0422\u0418",
    ja: "\u7ACB\u3061\u53BB\u308B",
    zh: "\u5C31\u6B64\u6536\u624B",
    ar: "\u0627\u0646\u0635\u0631\u0641",
  },

  /* And under it, what walking away is worth. */
  keepGold: {
    en: "KEEP {n}",
    tr: "{n} KALSIN",
    fr: "GARDER {n}",
    es: "CONSERVA {n}",
    ru: "\u041E\u0421\u0422\u0410\u0412\u0418\u0422\u042C {n}",
    ja: "{n} \u3092\u6301\u3061\u5E30\u308B",
    zh: "\u4FDD\u4F4F {n}",
    ar: "\u0627\u062D\u062A\u0641\u0638 \u0628\u0640 {n}",
  },

  /* Over the peek at the next floor's first foe. */
  waitingBelow: {
    en: "WAITING BELOW",
    tr: "A\u015EA\u011EIDA BEKL\u0130YOR",
    fr: "ATTEND EN BAS",
    es: "ESPERA ABAJO",
    ru: "\u0416\u0414\u0401\u0422 \u0412\u041D\u0418\u0417\u0423",
    ja: "\u4E0B\u3067\u5F85\u3063\u3066\u3044\u308B",
    zh: "\u5728\u4E0B\u9762\u7B49\u7740",
    ar: "\u064A\u0646\u062A\u0638\u0631 \u0641\u064A \u0627\u0644\u0623\u0633\u0641\u0644",
  },

  /* The way out of the card a fight opens on. The source writes this one into its
   * markup as well, and it is the single most-pressed word in the game. */
  fightBtn: {
    en: "FIGHT",
    tr: "SAVA\u015E",
    fr: "COMBATTRE",
    es: "LUCHAR",
    ru: "\u0412 \u0411\u041E\u0419",
    ja: "\u305F\u305F\u304B\u3046",
    zh: "\u6218\u6597",
    ar: "\u0642\u0627\u062A\u0644",
  },

  /* The kicker over an event. The source's own constant, and the only place
   * this violet is used. */
  betweenFloors: {
    en: "BETWEEN FLOORS",
    tr: "KATLAR ARASINDA",
    fr: "ENTRE DEUX \u00C9TAGES",
    es: "ENTRE PISOS",
    ru: "\u041C\u0415\u0416\u0414\u0423 \u042D\u0422\u0410\u0416\u0410\u041C\u0418",
    ja: "\u968E\u3068\u968E\u306E\u3042\u3044\u3060",
    zh: "\u5C42\u4E0E\u5C42\u4E4B\u95F4",
    ar: "\u0628\u064A\u0646 \u0627\u0644\u0637\u0648\u0627\u0628\u0642",
  },

  /* Under an event's outcome, once it has been read. */
  continueDescent: {
    en: "CONTINUE THE DESCENT",
    tr: "\u0130NMEYE DEVAM ET",
    fr: "POURSUIVRE LA DESCENTE",
    es: "CONTINUAR EL DESCENSO",
    ru: "\u041F\u0420\u041E\u0414\u041E\u041B\u0416\u0418\u0422\u042C \u0421\u041F\u0423\u0421\u041A",
    ja: "\u964D\u4E0B\u3092\u7D9A\u3051\u308B",
    zh: "\u7EE7\u7EED\u4E0B\u884C",
    ar: "\u0648\u0627\u0635\u0644 \u0627\u0644\u0646\u0632\u0648\u0644",
  },

  /* Added to a choice's hint when the purse cannot cover it. */
  notEnoughGold: {
    en: "NOT ENOUGH GOLD",
    tr: "YETERL\u0130 ALTIN YOK",
    fr: "PAS ASSEZ D'OR",
    es: "ORO INSUFICIENTE",
    ru: "\u041D\u0415 \u0425\u0412\u0410\u0422\u0410\u0415\u0422 \u0417\u041E\u041B\u041E\u0422\u0410",
    ja: "\u30B4\u30FC\u30EB\u30C9\u304C\u8DB3\u308A\u306A\u3044",
    zh: "\u91D1\u5E01\u4E0D\u8DB3",
    ar: "\u0644\u0627 \u064A\u0643\u0641\u064A \u0627\u0644\u0630\u0647\u0628",
  },

  /* The bazaar's buying shelf and what a relic off it costs. */
  forSale: {
    en: "FOR SALE \u00B7 {n}g",
    tr: "SATILIK \u00B7 {n}g",
    fr: "\u00C0 VENDRE \u00B7 {n}g",
    es: "EN VENTA \u00B7 {n}g",
    ru: "\u0412 \u041F\u0420\u041E\u0414\u0410\u0416\u0415 \u00B7 {n}g",
    ja: "\u8CA9\u58F2\u4E2D \u00B7 {n}g",
    zh: "\u51FA\u552E \u00B7 {n}g",
    ar: "\u0644\u0644\u0628\u064A\u0639 \u00B7 {n}g",
  },

  /* And its waking shelf. The word for a relic is the one the draft
   * already uses, so the two screens name the same thing the same way. */
  awakenRelic: {
    en: "AWAKEN A RELIC \u00B7 {n}g",
    tr: "B\u0130R KALINTIYI UYANDIR \u00B7 {n}g",
    fr: "\u00C9VEILLER UNE RELIQUE \u00B7 {n}g",
    es: "DESPERTAR UNA RELIQUIA \u00B7 {n}g",
    ru: "\u041F\u0420\u041E\u0411\u0423\u0414\u0418\u0422\u042C \u0420\u0415\u041B\u0418\u041A\u0412\u0418\u042E \u00B7 {n}g",
    ja: "\u30EC\u30EA\u30C3\u30AF\u3092\u899A\u9192\u3055\u305B\u308B \u00B7 {n}g",
    zh: "\u89C9\u9192\u4E00\u4EF6\u5723\u7269 \u00B7 {n}g",
    ar: "\u0623\u064A\u0642\u0638 \u0623\u062B\u0631\u0627\u064B \u00B7 {n}g",
  },

  /* The way out of the bazaar, which is also the way on to floor eight. */
  leaveShop: {
    en: "LEAVE THE SHOP",
    tr: "D\u00DCKK\u00C2NDAN \u00C7IK",
    fr: "QUITTER LA BOUTIQUE",
    es: "SALIR DE LA TIENDA",
    ru: "\u041F\u041E\u041A\u0418\u041D\u0423\u0422\u042C \u041B\u0410\u0412\u041A\u0423",
    ja: "\u5E97\u3092\u51FA\u308B",
    zh: "\u79BB\u5F00\u5546\u5E97",
    ar: "\u063A\u0627\u062F\u0631 \u0627\u0644\u0645\u062A\u062C\u0631",
  },

  /* The bazaar's own kicker. Not "cleared" — this floor is walked through rather
   * than fought, and calling it cleared would claim a fight that never happened. */
  relicShop: {
    en: "FLOOR {n} \u00B7 RELIC SHOP",
    tr: "KAT {n} \u00B7 KALINTI D\u00DCKK\u00C2NI",
    fr: "\u00C9TAGE {n} \u00B7 BOUTIQUE DE RELIQUES",
    es: "PISO {n} \u00B7 TIENDA DE RELIQUIAS",
    ru: "\u042D\u0422\u0410\u0416 {n} \u00B7 \u041B\u0410\u0412\u041A\u0410 \u0420\u0415\u041B\u0418\u041A\u0412\u0418\u0419",
    ja: "{n}\u968E \u00B7 \u30EC\u30EA\u30C3\u30AF\u5546\u5E97",
    zh: "\u7B2C {n} \u5C42 \u00B7 \u5723\u7269\u5546\u5E97",
    ar: "\u0627\u0644\u0637\u0627\u0628\u0642 {n} \u00B7 \u0645\u062A\u062C\u0631 \u0627\u0644\u0622\u062B\u0627\u0631",
  },

  /* Over the price of rising. Sparks outlive a run, which is why this is
   * the only screen in a delve that spends something other than gold. */
  spendSparks: {
    en: "SPEND SPARKS",
    tr: "KIVILCIM HARCA",
    fr: "D\u00C9PENSER DES \u00C9TINCELLES",
    es: "GASTAR CHISPAS",
    ru: "\u041F\u041E\u0422\u0420\u0410\u0422\u0418\u0422\u042C \u0418\u0421\u041A\u0420\u042B",
    ja: "\u30B9\u30D1\u30FC\u30AF\u3092\u4F7F\u3046",
    zh: "\u6D88\u8017\u706B\u82B1",
    ar: "\u0623\u0646\u0641\u0642 \u0627\u0644\u0634\u0631\u0627\u0631\u0627\u062A",
  },

  /* And what is left afterwards, which is what a delver spending their
   * whole balance actually wants to know. */
  sparksLeft: {
    en: "{n} LEFT",
    tr: "{n} KALIR",
    fr: "IL EN RESTE {n}",
    es: "QUEDAN {n}",
    ru: "\u041E\u0421\u0422\u0410\u041D\u0415\u0422\u0421\u042F {n}",
    ja: "\u6B8B\u308A {n}",
    zh: "\u5269\u4F59 {n}",
    ar: "\u064A\u062A\u0628\u0642\u0649 {n}",
  },

  /* Or, for a delver who cannot pay, by how much. */
  sparksShort: {
    en: "{n} SHORT",
    tr: "{n} EKS\u0130K",
    fr: "IL MANQUE {n}",
    es: "FALTAN {n}",
    ru: "\u041D\u0415 \u0425\u0412\u0410\u0422\u0410\u0415\u0422 {n}",
    ja: "{n} \u8DB3\u308A\u306A\u3044",
    zh: "\u8FD8\u5DEE {n}",
    ar: "\u064A\u0646\u0642\u0635\u0643 {n}",
  },
};

let added = 0;
for (const [key, byLang] of Object.entries(ADDED)) {
  for (const id of LOCALE_IDS) {
    if (key in LOCALES[id]) {
      warn(`added string "${key}" now exists in ${id} — the source has caught up, drop ours`);
      continue;
    }
    LOCALES[id][key] = byLang[id] ?? byLang.en;
    added++;
  }
}
console.log(`  + ${added} added strings across ${LOCALE_IDS.length} languages`);

for (const id of LOCALE_IDS) write(`locales/${id}.json`, LOCALES[id]);

/* ---------- 2. relics ---------- */

console.log("\nrelics");
const ITEMS = evalLiteral("ITEMS");
const NEWR = evalLiteral("NEWR");
const RELIC_ICON = evalLiteral("RELIC_ICON");
const NATIVE_TRIGGER = evalLiteral("NATIVE_TRIGGER"); // dead in JS, but real design intent
const EN = LOCALES.en;

const relicText = (id) => {
  const fromStrings = EN[`it_${id}_n`] != null;
  if (fromStrings) return { name: EN[`it_${id}_n`], desc: EN[`it_${id}_d`], source: "strings" };
  const n = NEWR[id];
  if (!n) { warn(`no text for relic ${id}`); return { name: id, desc: "", source: "missing" }; }
  return { name: n.n, desc: n.d, flavor: n.fl, passive: n.pas, nativeText: n.nat, activeText: n.act, source: "NEWR" };
};

/* What a relic SAYS on its own card, which is a different table from what it is called.
   RELIC_META is written by hand for 47 relics and then filled in from NEWR for anything it
   missed — that fill-in is the source's own line and is repeated here rather than resolved,
   because a relic that appears in both is described by RELIC_META and its NEWR text is dead.
   AWAKE_TEXT is what awakening a relic DOES, which the card promises before it happens. */
const RELIC_META = evalLiteral("RELIC_META");
const AWAKE_TEXT = evalLiteral("AWAKE_TEXT");
for (const k in NEWR) {
  if (!RELIC_META[k]) RELIC_META[k] = { fl: NEWR[k].fl, pas: NEWR[k].pas, nat: NEWR[k].nat, act: NEWR[k].act };
}

const relicLore = (id) => {
  const m = RELIC_META[id];
  if (!m) { warn(`no card text for relic ${id}`); return null; }
  return {
    flavour: m.fl || null,
    passive: m.pas || null,
    native: m.nat || null,
    activation: m.act || null,
    awake: AWAKE_TEXT[id] || null,
  };
};

const relics = Object.entries(ITEMS).map(([id, it]) => ({
  id,
  kind: it.kind,
  glyph: it.g,
  stackable: !!it.stack,
  modes: it.modes || ["delve", "versus"],
  emits: it.emits || [],
  reacts: it.reacts || [],
  wheel: it.wheel || null,
  nativeTrigger: NATIVE_TRIGGER[id] || null,
  icon: RELIC_ICON[id] ? { col: RELIC_ICON[id][0], row: RELIC_ICON[id][1] } : null,
  text: relicText(id),
  lore: relicLore(id),
}));
for (const r of relics) if (!r.icon) warn(`relic ${r.id} has no icon cell`);
write("relics.json", relics);

/* the ones the engine implements but ITEMS never exposes — cut, but recorded.
   We check each against the engine source so the triage doc states, per relic,
   whether live code paths exist for it (they all do, today). */
const ENGINE = SRC.slice(SRC.indexOf("  simulateFloor(st, pack, rng)"), SRC.indexOf("  lineFor(e)"));
const LEDGER = SRC.slice(SRC.indexOf("function heroStatRows(ctx, stat)"), SRC.indexOf("function heroCtxOf(st, foeRank)"));
const refs = (hay, id) => (hay.match(new RegExp(`"${id}"`, "g")) || []).length;
const cut = Object.keys(NEWR)
  .filter((id) => !(id in ITEMS))
  .map((id) => ({
    id,
    ...NEWR[id],
    engineRefs: refs(ENGINE, id),
    ledgerRefs: refs(LEDGER, id),
    totalRefs: refs(SRC, id),
  }));
write("relics-cut.json", cut);
writeCutDoc(cut);

/* ---------- 3. kinds & sockets ---------- */

console.log("\nkinds & sockets");
write("kinds.json", evalLiteral("KIND_META"));
/* The engine's trigger BUS is wider than the socket catalogue: fireTrig() is called with
   channels that no purchasable TRIGGER exposes, so those calls can never match a socket.
   Derive both sets from the source so the asymmetry is visible instead of assumed. */
const busTriggers = [...new Set(
  [...SRC.matchAll(/fireTrig\("(t_[a-z]+)"/g)].map((m) => m[1])
)].sort();
const TRIGGERS = evalLiteral("TRIGGERS");
write("sockets.json", {
  triggers: TRIGGERS,
  emitters: evalLiteral("EMITTERS"),
  busTriggers,
  unsocketableBusTriggers: busTriggers.filter((t) => !(t in TRIGGERS)),
});

/* ---------- 4. dungeons ---------- */

console.log("\ndungeons");
write("dungeons.json", evalLiteral("DUNGEONS"));

/* ---------- 4b. the palette ---------- */

/* A hero's pixels are ROLE KEYS rather than colours — one letter meaning "hair", or "the dark
   side of the outfit" — and a palette turns keys into colours at draw time. That is what lets
   the Changing Room recolour a delver without touching a sprite, so the table of families is
   content in exactly the way the relic table is. */

console.log("\npalette");
write("palette.json", {
  families: evalLiteral("FAMILIES"),
  solos: evalLiteral("SOLOS"),
  shade: evalLiteral("SHADE_DEFAULTS"),
});

/* ---------- 4c. the hero rig ---------- */

/* The registry a hero pack is drawn against: the canvas, the wardrobe slots, the animation
   states and what every role key means. A pack declares its own states so it can be validated
   against them, but the REGISTRY is what decides how long a state runs and how many frames it
   has — a distinction that is easy to miss and changes every animation if you get it wrong. */

console.log("\nhero rig");
const packLit = evalLiteral("PACK");
write("hero.json", {
  defaultSize: 32,
  slots: packLit.SLOTS,
  states: packLit.STATES,
  roles: packLit.ROLES,
});


/* ---------- 5. enemies ---------- */

console.log("\nenemies");
const ENEMY_G = evalLiteral("ENEMY_G");
const ENEMY_ROW = evalLiteral("ENEMY_ROW");
const ladderM = /const LADDER = (\[[^\]]*\]);/.exec(SRC);
const spareM = /const SPARE = (\d+)/.exec(SRC);
if (!ladderM) warn("LADDER not found in packFor");
write("enemies.json", {
  species: ENEMY_G.map((name, idx) => ({ idx, id: name, sheetRow: ENEMY_ROW[idx] })),
  sheet: { file: "assets/enemies-hoard.png", cols: 3, rows: 13, cell: 64, columnIsRank: ["guard", "elite", "boss"] },
  ladder: ladderM ? JSON.parse(ladderM[1]) : null,
  spare: spareM ? Number(spareM[1]) : null,
  kingSpecies: 9,
  notes: "Column = rank variant, row = species. LADDER is floor-order; SPARE is the king's honour guard.",
});

/* ---------- 6. events ---------- */

console.log("\nevents");
const EVENTS = evalLiteral("EVENTS");
write("events.json", EVENTS.map((e, i) => ({
  index: i, cat: e.cat, title: e.title, art: e.art, text: e.text,
  choices: (e.choices || []).map((c) => ({
    label: c.label, hint: c.hint || null, cost: c.cost || null, run: c.run,
  })),
})));

/* ---------- 7. progression & constants ---------- */

console.log("\nprogression & constants");
const META = evalLiteral("META");
write("progression.json", {
  structuralPerks: META.STRUCT,
  xpSteps: META.XP_STEPS,
  xpFloor: META.XP_FLOOR,
  needFormula: META.need,
  bonusesFormula: META.bonuses,
  tierMult: META.tierMult,
  achievements: META.ACHV,
});
write("constants.json", {
  ...scalars("MAX_FLOOR", "CHAIN_CAP", "SUPPORTER_SPARKS", "REVIVE_SPARKS",
             "SHOP_FLOOR", "SHOP_BUY", "SHOP_UP", "EV_MIN_SPD", "EV_MIN_DEF",
             "SHEET_COLS", "SHEET_ROWS", "SHEET_CELL"),
  hallAspect: [650, 181],
  defenseK: 20,
  merchantLines: evalLiteral("MERCHANT_LINES"),
});

/* ---------- manifest ---------- */

const manifest = {
  generated: new Date().toISOString(),
  source: "Daily Delve.dc.html",
  counts: {
    relics: relics.length,
    relicsCut: cut.length,
    kinds: Object.keys(evalLiteral("KIND_META")).length,
    dungeons: evalLiteral("DUNGEONS").length,
    colourFamilies: evalLiteral("FAMILIES").length,
    events: EVENTS.length,
    species: ENEMY_G.length,
    triggers: Object.keys(evalLiteral("TRIGGERS")).length,
    emitters: Object.keys(evalLiteral("EMITTERS")).length,
    locales: LOCALE_IDS.length,
  },
  localeIds: LOCALE_IDS,
  needsHandPort: [
    "events.json → choices[].run: outcome closures, port to C# EventOutcome handlers",
    "progression.json → needFormula / bonusesFormula / tierMult: port to Progression.cs",
    "progression.json → achievements[].ok: predicates read save state, port to C#",
  ],
  warnings,
};
write("manifest.json", manifest);

console.log(`\ndone — ${warnings.length} warning(s)\n`);
