/*
 * Content code generator.
 *
 *   node Tools/extract/gen-csharp.mjs      (run after extract.mjs)
 *
 * Turns Tools/out/*.json into the structural C# content layer in
 * Assets/GameAssets/Core/Content/. Invariant 8 of the port plan: content is
 * generated, never transcribed — 50 relics typed by hand is 50 chances to be wrong.
 *
 * Only STRUCTURAL facts are generated here: identity, kind, stacking, mode gating,
 * bus channels, native trigger. These are code-shaped and change only when the game
 * design changes. Designer-tunable numbers belong in ScriptableObjects later.
 *
 * Generated files are checked in so Core stays self-contained: no JSON loading, no
 * asset dependency, and the engine is testable outside Unity.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "Tools", "out");
const GEN = join(ROOT, "Assets", "GameAssets", "Core", "Content");
const load = (f) => JSON.parse(readFileSync(join(OUT, f), "utf8"));

const relics = load("relics.json");
const dungeons = load("dungeons.json");
const palette = load("palette.json");
const rig = load("hero.json");

/* Role keys are single characters and several of them are punctuation, so they are emitted as
   escaped C# char literals rather than trusted to survive as source text. */
const asChar = (k) => {
  const c = [...k][0];
  const code = c.codePointAt(0);
  if (c === "'") return "'\\''";
  if (c === "\\") return "'\\\\'";
  return code >= 32 && code < 127 ? `'${c}'` : `'\\u${code.toString(16).padStart(4, "0")}'`;
};
const kinds = load("kinds.json");

/* The captured prose. It comes from Tools/corpus/ rather than Tools/out/ because it was
   read out of the RUNNING source by Tools/capture/*.mjs — the halls' paragraphs and the
   bestiary's lines are written into markup rather than declared in a table, so there is no
   literal for the extractor to brace-match. Both files are gates in their own right and
   are regenerated by the capture scripts, not by hand. */
const corpus = (f) => JSON.parse(readFileSync(join(ROOT, "Tools", "corpus", f), "utf8"));
const hallProse = corpus("halls.json").halls;
const foeProse = corpus("foes.json").lore;
const sockets = load("sockets.json");

/* ---------- identifiers ---------- */

/** "Alchemist's Vial" -> AlchemistsVial. Readable, and derived rather than invented. */
function pascal(text) {
  return text
    .normalize("NFD").replace(/[̀-ͯ]/g, "")   // strip accents
    .replace(/[^A-Za-z0-9 ]/g, "")                       // drop apostrophes, punctuation
    .split(/\s+/).filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

const names = new Map();
for (const r of relics) {
  const name = pascal(r.text.name);
  if (!/^[A-Za-z]/.test(name)) throw new Error(`bad identifier for ${r.id}: ${name}`);
  if ([...names.values()].includes(name)) throw new Error(`duplicate identifier ${name} (${r.id})`);
  names.set(r.id, name);
}

const kindName = (k) => k[0] + k.slice(1).toLowerCase();          // GUARD -> Guard
const socketName = (s) => pascal(s.replace(/^[te]_/, "").replace(/([a-z])([A-Z])/g, "$1 $2"));

const channels = [...new Set(relics.flatMap((r) => [...r.emits, ...r.reacts]))].sort();

const header = (extra) =>
  `// <auto-generated>\n` +
  `//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.\n` +
  `//   Do not edit by hand — re-run the generator instead.\n` +
  (extra ? `//   ${extra}\n` : "") +
  `// </auto-generated>\n`;

const write = (file, body) => {
  mkdirSync(GEN, { recursive: true });
  writeFileSync(join(GEN, file), body.replace(/\n/g, "\r\n"), "utf8");
  console.log(`  → Assets/GameAssets/Core/Content/${file}`);
};

/* ---------- RelicKind ---------- */

write("RelicKind.cs", header(`${Object.keys(kinds).length} kinds`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>The eight relic families. Set bonuses trigger at 3, 5 and 7 of a kind.</summary>
    public enum RelicKind
    {
${Object.keys(kinds).map((k, i) => `        ${kindName(k)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- Channel ---------- */

write("Channel.cs", header(`${channels.length} bus channels used by relic emits/reacts`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// Event channels on the chain bus. A relic <c>emits</c> some and <c>reacts</c> to others;
    /// a relic is only "live" if something in the loadout can produce a channel it reacts to.
    /// </summary>
    public enum Channel
    {
${channels.map((c, i) => `        ${pascal(c)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- SocketTrigger / SocketEmitter ---------- */

const trigList = Object.keys(sockets.triggers);
const emitList = Object.keys(sockets.emitters);

write("SocketComponent.cs", header(`${trigList.length} triggers, ${emitList.length} emitters`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// What fires a socketed relic. Bought at the bazaar and attached to ONE COPY of a relic,
    /// which is why sockets are keyed by inventory index rather than by relic id.
    /// </summary>
    public enum SocketTrigger
    {
        None = 0,
${trigList.map((t, i) => `        ${socketName(t)} = ${i + 1},`).join("\n")}
    }

    /// <summary>What a socketed relic additionally does when it activates.</summary>
    public enum SocketEmitter
    {
        None = 0,
${emitList.map((e, i) => `        ${socketName(e)} = ${i + 1},`).join("\n")}
    }
}
`);

/* ---------- RelicId ---------- */

write("RelicId.cs", header(`${relics.length} relics in the draft pool`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// Every relic that can be drafted. Ordered as the source pool orders them.
    /// </summary>
    /// <remarks>
    /// This is the 50 reachable relics only. A further 28 have finished text and live code
    /// paths in the JS build but are absent from its draft table, so nothing can ever offer
    /// them; they are cut and recorded in docs/relics-cut.md.
    /// </remarks>
    public enum RelicId
    {
        None = -1,
${relics.map((r, i) => `        ${names.get(r.id)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- RelicCatalog ---------- */

const modeFlag = (modes) =>
  modes.includes("delve") && modes.includes("versus") ? "GameModes.Both"
    : modes.includes("delve") ? "GameModes.Delve" : "GameModes.Versus";

const chanList = (arr) => arr.length
  ? `new[] { ${arr.map((c) => `Channel.${pascal(c)}`).join(", ")} }`
  : "EmptyChannels";

const rows = relics.map((r, i) => {
  const trig = r.nativeTrigger && trigList.includes(r.nativeTrigger)
    ? `SocketTrigger.${socketName(r.nativeTrigger)}` : "SocketTrigger.None";
  return `            new RelicDef(RelicId.${names.get(r.id)}, "${r.id}", RelicKind.${kindName(r.kind)}, ` +
         `${r.stackable ? "true" : "false"}, ${modeFlag(r.modes)}, ` +
         `${chanList(r.emits)}, ${chanList(r.reacts)}, ${trig}),`;
}).join("\n");

write("RelicCatalog.cs", header(`structural facts for ${relics.length} relics`) +
`
using System;
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>Which modes a relic may appear in.</summary>
    [Flags]
    public enum GameModes
    {
        None = 0,
        Delve = 1,
        Versus = 2,
        Both = Delve | Versus,
    }

    /// <summary>Structural definition of one relic. Immutable, generated from the source game.</summary>
    public sealed class RelicDef
    {
        public readonly RelicId Id;

        /// <summary>The source game's string id, e.g. "whetstone". Used by the corpus differ.</summary>
        public readonly string Key;

        public readonly RelicKind Kind;

        /// <summary>Whether a second copy adds a further effect rather than being wasted.</summary>
        public readonly bool Stackable;

        public readonly GameModes Modes;

        /// <summary>Channels this relic puts onto the bus when it activates.</summary>
        public readonly Channel[] Emits;

        /// <summary>Channels that activate this relic.</summary>
        public readonly Channel[] Reacts;

        /// <summary>The bus channel this relic natively listens on, if any.</summary>
        public readonly SocketTrigger NativeTrigger;

        public RelicDef(RelicId id, string key, RelicKind kind, bool stackable, GameModes modes,
            Channel[] emits, Channel[] reacts, SocketTrigger nativeTrigger)
        {
            Id = id;
            Key = key;
            Kind = kind;
            Stackable = stackable;
            Modes = modes;
            Emits = emits;
            Reacts = reacts;
            NativeTrigger = nativeTrigger;
        }
    }

    /// <summary>
    /// The relic table. Static and generated so that Core needs no JSON loading, no
    /// ScriptableObjects, and no Unity — which is what lets the engine be tested headlessly.
    /// </summary>
    public static class RelicCatalog
    {
        private static readonly Channel[] EmptyChannels = new Channel[0];

        public static readonly IReadOnlyList<RelicDef> All = new[]
        {
${rows}
        };

        public const int Count = ${relics.length};

        private static readonly Dictionary<string, RelicId> ByKey = BuildKeyLookup();

        private static Dictionary<string, RelicId> BuildKeyLookup()
        {
            var map = new Dictionary<string, RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                map[All[i].Key] = All[i].Id;
            }

            return map;
        }

        public static RelicDef Get(RelicId id)
        {
            return All[(int)id];
        }

        public static RelicKind KindOf(RelicId id)
        {
            return All[(int)id].Kind;
        }

        /// <summary>Source-game string id for a relic, e.g. "whetstone".</summary>
        public static string KeyOf(RelicId id)
        {
            return All[(int)id].Key;
        }

        /// <summary>Resolve a source-game string id. Returns false for cut or unknown relics.</summary>
        public static bool TryParse(string key, out RelicId id)
        {
            return ByKey.TryGetValue(key, out id);
        }

        /// <summary>Relics that can appear in the given mode.</summary>
        public static List<RelicId> PoolFor(GameModes mode)
        {
            var pool = new List<RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                if ((All[i].Modes & mode) != 0)
                {
                    pool.Add(All[i].Id);
                }
            }

            return pool;
        }
    }
}
`);

/* ---------- DungeonCatalog ---------- */

/* The multiplier is a TABLE and not a formula. Its first five entries are exact powers of 1.1
   and the rest are rounded to four places, so anything that computes the power scores the deep
   halls a point out. Emitting the literals is what keeps that from being re-derived. */
const halls = dungeons.map((d) => {
  const boss = d.bossRelics.length
    ? `new[] { ${d.bossRelics.map((r) => `RelicId.${names.get(r)}`).join(", ")} }`
    : "NoRelics";
  const said = hallProse[d.id - 1];
  if (!said) throw new Error(`no captured prose for hall ${d.id}`);
  return `            new DungeonDef(${d.id}, ${d.lvl}, "${d.name}", "${d.art}", ` +
         `${d.mult}, ${boss}, ${d.ghoolemBoss ? "true" : "false"},` + "\n" +
         `                ${JSON.stringify(said.blurb)},` + "\n" +
         `                ${JSON.stringify(said.lore)}),`;
}).join("\n");

write("DungeonCatalog.cs", header(`${dungeons.length} halls`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One hall of the Hoard: what it is worth, and what its boss carries.</summary>
    public sealed class DungeonDef
    {
        /// <summary>Which hall this is, counting from one.</summary>
        public readonly int Tier;

        /// <summary>The delver level at which this hall is meant to be attempted.</summary>
        public readonly int Level;

        public readonly string Name;

        public readonly string Art;

        /// <summary>
        /// What a run in this hall is worth, applied to the foes inside it and to the score.
        /// </summary>
        /// <remarks>
        /// A table, not a formula. The first five entries are exact powers of 1.1 and the rest
        /// are rounded to four places — 1.6105 where the power is 1.61051 — so computing the
        /// power instead of reading this scores the deep halls a point out.
        /// </remarks>
        public readonly double Multiplier;

        /// <summary>The relic kit every boss in this hall carries.</summary>
        public readonly IReadOnlyList<RelicId> BossRelics;

        /// <summary>When set, the Ghoolem replaces this hall's bosses below the first floor.</summary>
        public readonly bool GhoolemBoss;

        /// <summary>The line shown on arriving: one sentence about what the hall feels like.</summary>
        /// <remarks>
        /// English, and that is the source's doing rather than an omission. The halls' prose is
        /// written as literals in its markup and never passes through its translation function,
        /// so it reads the same in every locale the game ships.
        ///
        /// Read from the source by <c>Tools/capture/halls.mjs</c> rather than typed. Ten
        /// paragraphs transcribed by hand is ten chances to drop a word nobody will ever notice
        /// is missing — prose is the one kind of content where a mistake reads as intentional.
        /// </remarks>
        public readonly string Blurb;

        /// <summary>The paragraph the dungeon list shows beside the hall's numbers.</summary>
        public readonly string Lore;

        public DungeonDef(int tier, int level, string name, string art, double multiplier,
            IReadOnlyList<RelicId> bossRelics, bool ghoolemBoss, string blurb, string lore)
        {
            Tier = tier;
            Level = level;
            Name = name;
            Art = art;
            Multiplier = multiplier;
            BossRelics = bossRelics;
            GhoolemBoss = ghoolemBoss;
            Blurb = blurb;
            Lore = lore;
        }
    }

    /// <summary>The halls, in order.</summary>
    public static class DungeonCatalog
    {
        private static readonly RelicId[] NoRelics = new RelicId[0];

        public static readonly IReadOnlyList<DungeonDef> All = new List<DungeonDef>
        {
${halls}
        };

        /// <summary>
        /// The hall at this tier, clamped to the ones that exist — which is what the source
        /// does everywhere it reads the table, so a saved tier past the end still resolves.
        /// </summary>
        public static DungeonDef Get(int tier)
        {
            int i = tier - 1;
            if (i < 0) i = 0;
            if (i >= All.Count) i = All.Count - 1;
            return All[i];
        }
    }
}
`);

/* ---------- HeroRig ---------- */

const stateRows = Object.keys(rig.states).map((name) => {
  const st = rig.states[name];
  return `            { "${name}", new HeroStateDef ` +
         `{ Frames = ${st.frames}, Ms = ${st.ms}, Mode = "${st.mode}" } },`;
}).join("\n");

const slotRows = rig.slots.map((s) => `            "${s}",`).join("\n");
const roleRows = Object.keys(rig.roles).map((k) =>
  `            { ${asChar(k)}, "${rig.roles[k]}" },`).join("\n");

write("HeroRig.cs", header(`${Object.keys(rig.states).length} states, ${rig.slots.length} slots`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>
    /// The rig every hero pack is drawn against.
    /// </summary>
    /// <remarks>
    /// A pack supplies the ART; this supplies the shape of it — which slots exist, how long each
    /// animation runs, and what every role key means.
    ///
    /// A pack declares its own states too, and those are used to VALIDATE it: a part claiming
    /// more frames than its state allows is malformed. They are not what the game animates from.
    /// The registry decides that, and a pack drawn with more frames than the registry claims
    /// simply animates fully. Reading the pack's numbers instead is a mistake that changes every
    /// animation in the game and looks, at a glance, like the more obvious thing to do.
    /// </remarks>
    public static class HeroRig
    {
        /// <summary>The canvas a pack is drawn on unless it says otherwise.</summary>
        public const int DefaultSize = ${rig.defaultSize};

        /// <summary>The wardrobe slots, in the order the registry lists them.</summary>
        public static readonly IReadOnlyList<string> Slots = new List<string>
        {
${slotRows}
        };

        /// <summary>How long each state runs, and how it ends.</summary>
        public static readonly IReadOnlyDictionary<string, HeroStateDef> States =
            new Dictionary<string, HeroStateDef>
        {
${stateRows}
        };

        /// <summary>What each role key means, for anything that shows an artist the palette.</summary>
        public static readonly IReadOnlyDictionary<char, string> Roles =
            new Dictionary<char, string>
        {
${roleRows}
        };
    }
}
`);

/* ---------- HeroPalette ---------- */

const familyRows = palette.families.map((f) =>
  `            new ColourFamily("${f.name}", ${asChar(f.base)}, ${asChar(f.dark)}, ` +
  `${asChar(f.light)}, "${f.hex}"),`).join("\n");

const soloRows = Object.keys(palette.solos).map((k) =>
  `            { ${asChar(k)}, "${palette.solos[k]}" },`).join("\n");

const sh = palette.shade;

write("HeroPalette.cs", header(`${palette.families.length} colour families`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One family of the palette: a base colour, and the two it derives.</summary>
    /// <remarks>
    /// The three keys are what a hero's pixels actually hold. A pixel saying <c>H</c> is hair,
    /// <c>h</c> is hair in shadow and <c>1</c> is hair catching the light — so recolouring a
    /// delver is a matter of handing the shader three different colours, not three sprites.
    /// </remarks>
    public sealed class ColourFamily
    {
        public readonly string Name;

        /// <summary>The key a pixel of the base colour carries.</summary>
        public readonly char Base;

        /// <summary>The key for the shaded side, derived from the base.</summary>
        public readonly char Dark;

        /// <summary>The key for the lit side, derived from the base.</summary>
        public readonly char Light;

        /// <summary>What the family is when the delver has chosen nothing.</summary>
        public readonly string DefaultHex;

        public ColourFamily(string name, char baseKey, char dark, char light, string defaultHex)
        {
            Name = name;
            Base = baseKey;
            Dark = dark;
            Light = light;
            DefaultHex = defaultHex;
        }
    }

    /// <summary>
    /// How far a family's derived colours move from its base.
    /// </summary>
    /// <remarks>
    /// Shared by every family unless one says otherwise, and exposed as data because the sprite
    /// studio lets an artist tune it and watch the whole wardrobe follow.
    /// </remarks>
    public sealed class ShadeParams
    {
        public double DarkMultiplier = ${sh.darkMult};
        public double DarkHue = ${sh.darkHue};
        public double DarkSaturation = ${sh.darkSat};

        public double LightMultiplier = ${sh.lightMult};
        public double LightHue = ${sh.lightHue};
        public double LightSaturation = ${sh.lightSat};
    }

    /// <summary>The families, the fixed colours, and the palette they make together.</summary>
    public static class HeroPalette
    {
        public static readonly IReadOnlyList<ColourFamily> Families = new List<ColourFamily>
        {
${familyRows}
        };

        /// <summary>
        /// Colours that are never recoloured: white, black and five greys between them.
        /// </summary>
        public static readonly IReadOnlyDictionary<char, string> Fixed =
            new Dictionary<char, string>
        {
${soloRows}
        };

        /// <summary>The colour the automatic silhouette outline is drawn in.</summary>
        public const char OutlineKey = '\\u0001';

        /// <summary>
        /// Keys that are not families but are painted anyway: the outline, and a dark default.
        /// </summary>
        public static readonly IReadOnlyDictionary<char, string> Extras =
            new Dictionary<char, string>
        {
            { 'd', "#191510" },
            { OutlineKey, "#0E0C08" },
        };

        /// <summary>
        /// Tokens in older art that mean a role which has since been renamed or merged away.
        /// </summary>
        /// <remarks>
        /// Art drawn before a role existed still carries the old letter, so the palette answers
        /// both. Dropping these would not fail loudly — the pixels would simply come out
        /// unpainted, which is why they are listed rather than left to be noticed.
        /// </remarks>
        public static readonly IReadOnlyDictionary<char, char> Aliases =
            new Dictionary<char, char>
        {
            { 'f', 'N' }, { 'i', 'E' }, { 'j', 'E' }, { 'm', 'y' },
            { 'S', 'W' }, { 's', 'w' }, { '7', '6' },
        };

        /// <summary>
        /// The whole palette, as the shader wants it: every role key against its colour.
        /// </summary>
        /// <param name="chosen">
        /// A delver's own colours, keyed by a family's BASE key. Anything unstated keeps the
        /// family's default, which is how a half-dressed delver still comes out whole.
        /// </param>
        public static Dictionary<char, Rgb> Build(IReadOnlyDictionary<char, string> chosen = null,
            ShadeParams shade = null)
        {
            shade = shade ?? new ShadeParams();
            var roles = new Dictionary<char, Rgb>(Families.Count * 3 + Fixed.Count);

            for (int i = 0; i < Families.Count; i++)
            {
                ColourFamily family = Families[i];

                string picked;
                if (chosen == null || !chosen.TryGetValue(family.Base, out picked))
                {
                    picked = family.DefaultHex;
                }

                Rgb baseColour = Rgb.Parse(picked);
                roles[family.Base] = baseColour;
                roles[family.Dark] = HeroColour.ApplyShade(baseColour, shade.DarkMultiplier,
                    shade.DarkHue, shade.DarkSaturation);
                roles[family.Light] = HeroColour.ApplyShade(baseColour, shade.LightMultiplier,
                    shade.LightHue, shade.LightSaturation);
            }

            foreach (KeyValuePair<char, string> extra in Extras)
            {
                roles[extra.Key] = Rgb.Parse(extra.Value);
            }

            foreach (KeyValuePair<char, string> solo in Fixed)
            {
                roles[solo.Key] = Rgb.Parse(solo.Value);
            }

            // Aliases resolve against the finished palette, so an alias of a family key picks up
            // whatever the delver chose for it.
            foreach (KeyValuePair<char, char> alias in Aliases)
            {
                Rgb target;
                if (roles.TryGetValue(alias.Value, out target)) roles[alias.Key] = target;
            }

            return roles;
        }
    }
}
`);

/* ---------- RelicArt ---------- */

/* Where each relic is drawn from. The sheet is 10x8 cells of 48px, which validate.mjs asserts
   against every recorded cell, so a relic that moved off the sheet fails Phase 0 rather than
   drawing the wrong icon.

   One relic — debtflesh — has no cell at all and falls back to a procedural glyph. That hole is
   recorded here rather than excused by hand later: the binding audit reads this list, so nobody
   can quiet a genuinely missing icon by typing its name into an exception. */
const ICON_COLS = 10;
const ICON_ROWS = 8;
const ICON_CELL = 48;

write("RelicArt.cs", header(`icon cells for ${relics.filter((r) => r.icon).length} of ${relics.length} relics`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>Where one relic's icon comes from.</summary>
    public sealed class RelicArtDef
    {
        public readonly RelicId Id;

        /// <summary>Column on the icon sheet, or <c>-1</c> when there is no cell for it.</summary>
        public readonly int Column;

        /// <summary>Row on the icon sheet, or <c>-1</c>.</summary>
        public readonly int Row;

        /// <summary>
        /// The procedural glyph it falls back to, which every relic has whether it needs it or not.
        /// </summary>
        public readonly string Glyph;

        public RelicArtDef(RelicId id, int column, int row, string glyph)
        {
            Id = id;
            Column = column;
            Row = row;
            Glyph = glyph;
        }

        /// <summary>Whether an icon was drawn for it.</summary>
        public bool OnTheSheet { get { return Column >= 0; } }
    }

    /// <summary>
    /// The icon sheet, cell by cell.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules — nothing in the engine reads this. It is in Core so that the
    /// importer which slices <c>relic-icons.png</c> and the audit which checks the slices agree
    /// by construction, and so that both can be tested without opening the Editor.
    /// </remarks>
    public static class RelicArt
    {
        public const int SheetColumns = ${ICON_COLS};
        public const int SheetRows = ${ICON_ROWS};

        /// <summary>Side of one cell, in pixels.</summary>
        public const int SheetCell = ${ICON_CELL};

        public static readonly IReadOnlyList<RelicArtDef> All = new[]
        {
${relics.map((r) => `            new RelicArtDef(RelicId.${names.get(r.id)}, ` +
  `${r.icon ? r.icon.col : -1}, ${r.icon ? r.icon.row : -1}, "${r.glyph}"),`).join("\n")}
        };

        public static RelicArtDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
`);

/* ---------- RelicText ---------- */

/* What a relic is CALLED, which is not one question but two. Nineteen of the fifty are in the
   locale tables under it_<id>_n and translate; the other thirty-one live in the expansion table
   in the source and are English wherever you read them. That split is a tracked gap in
   validate.mjs and it is carried here rather than flattened, so a line of the combat log can ask
   for a translation when one exists and fall back to the shipped English when it does not —
   instead of every relic name being English because one table was easier to read. */
write("RelicText.cs", header(`names for ${relics.length} relics, ${relics.filter((r) => r.text.source === "strings").length} of them translatable`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>What one relic is called.</summary>
    public sealed class RelicTextDef
    {
        public readonly RelicId Id;

        /// <summary>The shipped English name. Always present.</summary>
        public readonly string Name;

        /// <summary>
        /// The locale key its name lives under, or null when it has none.
        /// </summary>
        /// <remarks>
        /// Thirty-one of the fifty have none: they were added in the source's expansion table,
        /// which is English and was never handed to a translator. A caller asks for the key when
        /// there is one and shows <see cref="Name"/> when there is not.
        /// </remarks>
        public readonly string NameKey;

        /// <summary>
        /// What it does, in English, for a relic the source never translated.
        /// </summary>
        /// <remarks>
        /// Exactly one of this and <see cref="WhatKey"/> is set, and which one is the source's
        /// own split rather than the port's. Nineteen relics have their name and description in
        /// the locale tables under <c>it_&lt;id&gt;_n</c> and <c>it_&lt;id&gt;_d</c>. The rest
        /// live in an object called NEWR, in English, and the source reads NEWR FIRST — so a
        /// relic that appears in both is described by NEWR and its translation is never shown.
        ///
        /// Read from the source by <c>Tools/capture/relics.mjs</c>. Thirty-one descriptions
        /// typed by hand is thirty-one chances to change what a relic claims to do, which is the
        /// one kind of prose in this game a delver makes decisions on.
        /// </remarks>
        public readonly string What;

        /// <summary>The key its description is translated under, or null when it is not.</summary>
        public readonly string WhatKey;

        public RelicTextDef(RelicId id, string name, string nameKey, string what, string whatKey)
        {
            Id = id;
            Name = name;
            NameKey = nameKey;
            What = what;
            WhatKey = whatKey;
        }

        /// <summary>Whether this relic's name reaches a delver in their own language.</summary>
        public bool Translated { get { return NameKey != null; } }
    }

    /// <summary>
    /// The relic names, and which of them a translator has seen.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules. Nothing in the engine reads this; the combat log and the relic
    /// book do.
    /// </remarks>
    public static class RelicText
    {
        public static readonly IReadOnlyList<RelicTextDef> All = new[]
        {
${relics.map((r) => {
  const translated = r.text.source === "strings";
  return `            new RelicTextDef(RelicId.${names.get(r.id)}, ${JSON.stringify(r.text.name)}, ` +
    `${translated ? JSON.stringify("it_" + r.id + "_n") : "null"}, ` +
    `${translated ? "null" : JSON.stringify(r.text.desc)}, ` +
    `${translated ? JSON.stringify("it_" + r.id + "_d") : "null"}),`;
}).join("\n")}
        };

        public static RelicTextDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
`);

/* ---------- RelicLore ---------- */

/* What a relic's own card SAYS, which is a different table from what it is called. The source
   keeps four lines per relic — a flavour line, and up to three rule lines that the card labels
   PASSIVE / TRIGGER / ON ACTIVATION — plus a fifth for what awakening it would do.

   None of it goes through t(). Every one of these lines is English in all eight languages, in a
   modal a delver opens precisely BECAUSE they want to know what a relic does. That is the
   source's behaviour and it is carried rather than fixed, but it is carried where it can be
   counted: RelicLoreTests holds the total, so translating them later is a number that moves. */
write("RelicLore.cs", header(`card text for ${relics.length} relics, English only`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>What one relic's card says about itself.</summary>
    public sealed class RelicLoreDef
    {
        public readonly RelicId Id;

        /// <summary>The line in quotes. Every relic has one.</summary>
        public readonly string Flavour;

        /// <summary>What it does with no prompting, or null when it does nothing by itself.</summary>
        public readonly string Passive;

        /// <summary>What sets it off, or null when nothing does.</summary>
        public readonly string Native;

        /// <summary>
        /// What it does when it goes off, or null when it never goes off.
        /// </summary>
        /// <remarks>
        /// The card labels this differently depending on <see cref="Native"/>: a relic with a
        /// trigger of its own says ON ACTIVATION, and one without says IF RELAYED — the same
        /// text, and a true difference, because the second only ever fires through a socket.
        /// </remarks>
        public readonly string Activation;

        /// <summary>What awakening it would do, or null for the eleven that cannot awaken.</summary>
        public readonly string Awake;

        public RelicLoreDef(RelicId id, string flavour, string passive, string native,
            string activation, string awake)
        {
            Id = id;
            Flavour = flavour;
            Passive = passive;
            Native = native;
            Activation = activation;
            Awake = awake;
        }
    }

    /// <summary>
    /// The relic dossiers.
    /// </summary>
    /// <remarks>
    /// Presentation, not rules — nothing in the engine reads a word of this. What it describes
    /// is implemented in <c>Core/Run</c>, and the two can disagree without anything failing,
    /// which is the reason these lines are generated from the source rather than typed.
    /// </remarks>
    public static class RelicLore
    {
        public static readonly IReadOnlyList<RelicLoreDef> All = new[]
        {
${relics.map((r) => {
  const l = r.lore || {};
  const q = (v) => (v == null ? "null" : JSON.stringify(v));
  return `            new RelicLoreDef(RelicId.${names.get(r.id)}, ${q(l.flavour)}, ` +
    `${q(l.passive)}, ${q(l.native)}, ${q(l.activation)}, ${q(l.awake)}),`;
}).join("\n")}
        };

        public static RelicLoreDef Get(RelicId id)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Id == id) return All[i];
            }

            return null;
        }
    }
}
`);

/* ---------- SetCatalog ---------- */

/* Eight families, each with the same shape: a colour, and rules that switch on at three, five
   and seven of a kind. CURSE has only the first — it is the odd one out and the table says so
   rather than the code assuming three tiers everywhere.

   The tier text is English, like the relic cards and for the same reason. */
write("SetCatalog.cs", header(`${Object.keys(kinds).length} relic families, ` +
  `${Object.values(kinds).reduce((n, m) => n + Object.keys(m.tiers).length, 0)} tiers, English only`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One step of a set bonus: how many of a kind, and what that buys.</summary>
    public sealed class SetTier
    {
        /// <summary>How many relics of the kind are needed.</summary>
        public readonly int Needs;

        /// <summary>What it does, in English.</summary>
        public readonly string What;

        public SetTier(int needs, string what)
        {
            Needs = needs;
            What = what;
        }
    }

    /// <summary>One relic family and what collecting it is worth.</summary>
    public sealed class SetDef
    {
        public readonly RelicKind Kind;

        /// <summary>The name the game prints, upper case, as the source writes it.</summary>
        public readonly string Name;

        /// <summary>The family's colour, as <c>#RRGGBB</c>. Read with <see cref="Rgb.Parse"/>.</summary>
        public readonly string Hex;

        /// <summary>Its steps, in ascending order of how many are needed.</summary>
        public readonly IReadOnlyList<SetTier> Tiers;

        public SetDef(RelicKind kind, string name, string hex, IReadOnlyList<SetTier> tiers)
        {
            Kind = kind;
            Name = name;
            Hex = hex;
            Tiers = tiers;
        }
    }

    /// <summary>The eight relic families.</summary>
    public static class SetCatalog
    {
        public static readonly IReadOnlyList<SetDef> All = new[]
        {
${Object.entries(kinds).map(([k, m]) => {
  const tiers = Object.keys(m.tiers).map(Number).sort((a, b) => a - b)
    .map((t) => `new SetTier(${t}, ${JSON.stringify(m.tiers[t])})`).join(", ");
  return `            new SetDef(RelicKind.${kindName(k)}, ${JSON.stringify(k)}, ` +
    `${JSON.stringify(m.c)}, new[] { ${tiers} }),`;
}).join("\n")}
        };

        public static SetDef Get(RelicKind kind)
        {
            for (int i = 0; i < All.Count; i++)
            {
                if (All[i].Kind == kind) return All[i];
            }

            return null;
        }
    }
}
`);

/* ---------- EventArt ---------- */

/* Events are addressed by index everywhere, so their art is a list rather than a table. The
   stem of the filename is the id the binding uses, because that is the one thing the importer
   can see on disk and the audit can check without a second naming scheme in between. */
const events = load("events.json");
const stem = (art) => art.replace(/^.*\//, "").replace(/\.[a-z]+$/, "");

write("EventArt.cs", header(`art for ${events.length} dungeon events`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>
    /// What each dungeon event is illustrated with, indexed as the events themselves are.
    /// </summary>
    /// <remarks>
    /// The rules half lives in <c>DungeonEvents</c> and is hand-ported against the corpus. This
    /// is only the picture, kept apart so that changing an illustration never touches a file
    /// that decides what a choice costs.
    /// </remarks>
    public static class EventArt
    {
        /// <summary>Art id per event index. Position is the event's index.</summary>
        public static readonly IReadOnlyList<string> All = new[]
        {
${events.map((e) => `            "${stem(e.art)}",`).join("\n")}
        };

        public static string Get(int index) { return All[index]; }
    }
}
`);

/* ---------- EnemyCatalog ---------- */

/* Only the presentation half of the bestiary: what a species is called, and which row of the
   sheet it is drawn on. Which species owns which floor is a RULE and lives in
   EnemyPackGenerator, hand-ported and gated by the corpus — it is not repeated here.

   The sheet row is worth generating rather than typing. It is not the bestiary index: the
   artist drew them in a different order, so eleven of the thirteen disagree, and a transcription
   slip would put a bat where a rat should be with nothing to catch it but a human eye. */
const enemies = load("enemies.json");

write("EnemyCatalog.cs",
  header(`${enemies.species.length} species on a ${enemies.sheet.cols}x${enemies.sheet.rows} sheet`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One species in the bestiary: what it is called, and where it is drawn.</summary>
    public sealed class EnemyDef
    {
        /// <summary>Bestiary index. What the engine passes around.</summary>
        public readonly int Index;

        /// <summary>The source game's string id, e.g. "rat". Used to name its art.</summary>
        public readonly string Key;

        /// <summary>
        /// Which row of the sheet draws it — NOT the index. The two agree for two species.
        /// </summary>
        public readonly int SheetRow;

        /// <summary>The line the bestiary shows once a delver has met this species.</summary>
        /// <remarks>
        /// English in every locale, and the source says so itself: its comment over the array
        /// reads "EN, like the components". The species NAME is translated — key <c>en0</c>
        /// upward — and its card is not, which is a distinction worth keeping rather than
        /// tidying, because tidying it means inventing eight translations nobody wrote.
        ///
        /// Read from the source by <c>Tools/capture/foes.mjs</c>. Thirteen lines typed by hand
        /// is thirteen chances to drop a word, and a bestiary entry with a word missing still
        /// reads as a bestiary entry.
        /// </remarks>
        public readonly string Lore;

        public EnemyDef(int index, string key, int sheetRow, string lore)
        {
            Index = index;
            Key = key;
            SheetRow = sheetRow;
            Lore = lore;
        }
    }

    /// <summary>
    /// The bestiary, as far as drawing it is concerned.
    /// </summary>
    /// <remarks>
    /// Deliberately thin. Everything about how a species FIGHTS — which floor fields it, how it
    /// scales, which of them guards the King — is in <c>EnemyPackGenerator</c>, hand-ported
    /// against the corpus. This table exists so the art can be found without a second copy of
    /// the bestiary living in the Editor.
    /// </remarks>
    public static class EnemyCatalog
    {
        public static readonly IReadOnlyList<EnemyDef> All = new[]
        {
${enemies.species.map((s) => {
  const said = foeProse[s.idx];
  if (said == null) throw new Error(`no captured line for species ${s.id}`);
  return `            new EnemyDef(${s.idx}, "${s.id}", ${s.sheetRow},` + "\n" +
    `                ${JSON.stringify(said)}),`;
}).join("\n")}
        };

        /// <summary>What each sheet column shows: bare, armed, armed and shielded.</summary>
        /// <remarks>The King has no column of his own — he is drawn as a boss.</remarks>
        public static readonly IReadOnlyList<string> Ranks = new[]
        {
${enemies.sheet.columnIsRank.map((r) => `            "${r}",`).join("\n")}
        };

        public const int SheetColumns = ${enemies.sheet.cols};
        public const int SheetRows = ${enemies.sheet.rows};

        /// <summary>Side of one cell, in pixels.</summary>
        public const int SheetCell = ${enemies.sheet.cell};

        public static EnemyDef Get(int index) { return All[index]; }

        /// <summary>The id its art is bound under: the key, then the rank it is drawn at.</summary>
        public static string ArtId(int index, int column)
        {
            return All[index].Key + "/" + Ranks[column];
        }
    }
}
`);

console.log(`
  ${relics.length} relics, ${Object.keys(kinds).length} kinds, ` +
            `${channels.length} channels, ${trigList.length} triggers, ${emitList.length} emitters, ` +
            `${dungeons.length} halls, ${palette.families.length} colour families\n`);
