/*
 * Content code generator.
 *
 *   node Tools/extract/gen-csharp.mjs      (run after extract.mjs)
 *
 * Turns Tools/out/*.json into the structural C# content layer in
 * Assets/GameAssets/Core/Content/. Invariant 8 of the port plan: content is
 * generated, never transcribed — 50 relics typed by hand is 50 chances to be wrong.
 *
 * Only STRUCTURAL facts are generated here: identity, kind, stacking, mode gating,
 * bus channels, native trigger. These are code-shaped and change only when the game
 * design changes. Designer-tunable numbers belong in ScriptableObjects later.
 *
 * Generated files are checked in so Core stays self-contained: no JSON loading, no
 * asset dependency, and the engine is testable outside Unity.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "Tools", "out");
const GEN = join(ROOT, "Assets", "GameAssets", "Core", "Content");
const load = (f) => JSON.parse(readFileSync(join(OUT, f), "utf8"));

const relics = load("relics.json");
const dungeons = load("dungeons.json");
const palette = load("palette.json");
const kinds = load("kinds.json");
const sockets = load("sockets.json");

/* ---------- identifiers ---------- */

/** "Alchemist's Vial" -> AlchemistsVial. Readable, and derived rather than invented. */
function pascal(text) {
  return text
    .normalize("NFD").replace(/[̀-ͯ]/g, "")   // strip accents
    .replace(/[^A-Za-z0-9 ]/g, "")                       // drop apostrophes, punctuation
    .split(/\s+/).filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

const names = new Map();
for (const r of relics) {
  const name = pascal(r.text.name);
  if (!/^[A-Za-z]/.test(name)) throw new Error(`bad identifier for ${r.id}: ${name}`);
  if ([...names.values()].includes(name)) throw new Error(`duplicate identifier ${name} (${r.id})`);
  names.set(r.id, name);
}

const kindName = (k) => k[0] + k.slice(1).toLowerCase();          // GUARD -> Guard
const socketName = (s) => pascal(s.replace(/^[te]_/, "").replace(/([a-z])([A-Z])/g, "$1 $2"));

const channels = [...new Set(relics.flatMap((r) => [...r.emits, ...r.reacts]))].sort();

const header = (extra) =>
  `// <auto-generated>\n` +
  `//   Generated by Tools/extract/gen-csharp.mjs from Tools/out/*.json.\n` +
  `//   Do not edit by hand — re-run the generator instead.\n` +
  (extra ? `//   ${extra}\n` : "") +
  `// </auto-generated>\n`;

const write = (file, body) => {
  mkdirSync(GEN, { recursive: true });
  writeFileSync(join(GEN, file), body.replace(/\n/g, "\r\n"), "utf8");
  console.log(`  → Assets/GameAssets/Core/Content/${file}`);
};

/* ---------- RelicKind ---------- */

write("RelicKind.cs", header(`${Object.keys(kinds).length} kinds`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>The eight relic families. Set bonuses trigger at 3, 5 and 7 of a kind.</summary>
    public enum RelicKind
    {
${Object.keys(kinds).map((k, i) => `        ${kindName(k)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- Channel ---------- */

write("Channel.cs", header(`${channels.length} bus channels used by relic emits/reacts`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// Event channels on the chain bus. A relic <c>emits</c> some and <c>reacts</c> to others;
    /// a relic is only "live" if something in the loadout can produce a channel it reacts to.
    /// </summary>
    public enum Channel
    {
${channels.map((c, i) => `        ${pascal(c)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- SocketTrigger / SocketEmitter ---------- */

const trigList = Object.keys(sockets.triggers);
const emitList = Object.keys(sockets.emitters);

write("SocketComponent.cs", header(`${trigList.length} triggers, ${emitList.length} emitters`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// What fires a socketed relic. Bought at the bazaar and attached to ONE COPY of a relic,
    /// which is why sockets are keyed by inventory index rather than by relic id.
    /// </summary>
    public enum SocketTrigger
    {
        None = 0,
${trigList.map((t, i) => `        ${socketName(t)} = ${i + 1},`).join("\n")}
    }

    /// <summary>What a socketed relic additionally does when it activates.</summary>
    public enum SocketEmitter
    {
        None = 0,
${emitList.map((e, i) => `        ${socketName(e)} = ${i + 1},`).join("\n")}
    }
}
`);

/* ---------- RelicId ---------- */

write("RelicId.cs", header(`${relics.length} relics in the draft pool`) +
`
namespace RelicRun.Core.Content
{
    /// <summary>
    /// Every relic that can be drafted. Ordered as the source pool orders them.
    /// </summary>
    /// <remarks>
    /// This is the 50 reachable relics only. A further 28 have finished text and live code
    /// paths in the JS build but are absent from its draft table, so nothing can ever offer
    /// them; they are cut and recorded in docs/relics-cut.md.
    /// </remarks>
    public enum RelicId
    {
        None = -1,
${relics.map((r, i) => `        ${names.get(r.id)} = ${i},`).join("\n")}
    }
}
`);

/* ---------- RelicCatalog ---------- */

const modeFlag = (modes) =>
  modes.includes("delve") && modes.includes("versus") ? "GameModes.Both"
    : modes.includes("delve") ? "GameModes.Delve" : "GameModes.Versus";

const chanList = (arr) => arr.length
  ? `new[] { ${arr.map((c) => `Channel.${pascal(c)}`).join(", ")} }`
  : "EmptyChannels";

const rows = relics.map((r, i) => {
  const trig = r.nativeTrigger && trigList.includes(r.nativeTrigger)
    ? `SocketTrigger.${socketName(r.nativeTrigger)}` : "SocketTrigger.None";
  return `            new RelicDef(RelicId.${names.get(r.id)}, "${r.id}", RelicKind.${kindName(r.kind)}, ` +
         `${r.stackable ? "true" : "false"}, ${modeFlag(r.modes)}, ` +
         `${chanList(r.emits)}, ${chanList(r.reacts)}, ${trig}),`;
}).join("\n");

write("RelicCatalog.cs", header(`structural facts for ${relics.length} relics`) +
`
using System;
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>Which modes a relic may appear in.</summary>
    [Flags]
    public enum GameModes
    {
        None = 0,
        Delve = 1,
        Versus = 2,
        Both = Delve | Versus,
    }

    /// <summary>Structural definition of one relic. Immutable, generated from the source game.</summary>
    public sealed class RelicDef
    {
        public readonly RelicId Id;

        /// <summary>The source game's string id, e.g. "whetstone". Used by the corpus differ.</summary>
        public readonly string Key;

        public readonly RelicKind Kind;

        /// <summary>Whether a second copy adds a further effect rather than being wasted.</summary>
        public readonly bool Stackable;

        public readonly GameModes Modes;

        /// <summary>Channels this relic puts onto the bus when it activates.</summary>
        public readonly Channel[] Emits;

        /// <summary>Channels that activate this relic.</summary>
        public readonly Channel[] Reacts;

        /// <summary>The bus channel this relic natively listens on, if any.</summary>
        public readonly SocketTrigger NativeTrigger;

        public RelicDef(RelicId id, string key, RelicKind kind, bool stackable, GameModes modes,
            Channel[] emits, Channel[] reacts, SocketTrigger nativeTrigger)
        {
            Id = id;
            Key = key;
            Kind = kind;
            Stackable = stackable;
            Modes = modes;
            Emits = emits;
            Reacts = reacts;
            NativeTrigger = nativeTrigger;
        }
    }

    /// <summary>
    /// The relic table. Static and generated so that Core needs no JSON loading, no
    /// ScriptableObjects, and no Unity — which is what lets the engine be tested headlessly.
    /// </summary>
    public static class RelicCatalog
    {
        private static readonly Channel[] EmptyChannels = new Channel[0];

        public static readonly IReadOnlyList<RelicDef> All = new[]
        {
${rows}
        };

        public const int Count = ${relics.length};

        private static readonly Dictionary<string, RelicId> ByKey = BuildKeyLookup();

        private static Dictionary<string, RelicId> BuildKeyLookup()
        {
            var map = new Dictionary<string, RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                map[All[i].Key] = All[i].Id;
            }

            return map;
        }

        public static RelicDef Get(RelicId id)
        {
            return All[(int)id];
        }

        public static RelicKind KindOf(RelicId id)
        {
            return All[(int)id].Kind;
        }

        /// <summary>Source-game string id for a relic, e.g. "whetstone".</summary>
        public static string KeyOf(RelicId id)
        {
            return All[(int)id].Key;
        }

        /// <summary>Resolve a source-game string id. Returns false for cut or unknown relics.</summary>
        public static bool TryParse(string key, out RelicId id)
        {
            return ByKey.TryGetValue(key, out id);
        }

        /// <summary>Relics that can appear in the given mode.</summary>
        public static List<RelicId> PoolFor(GameModes mode)
        {
            var pool = new List<RelicId>(All.Count);
            for (int i = 0; i < All.Count; i++)
            {
                if ((All[i].Modes & mode) != 0)
                {
                    pool.Add(All[i].Id);
                }
            }

            return pool;
        }
    }
}
`);

/* ---------- DungeonCatalog ---------- */

/* The multiplier is a TABLE and not a formula. Its first five entries are exact powers of 1.1
   and the rest are rounded to four places, so anything that computes the power scores the deep
   halls a point out. Emitting the literals is what keeps that from being re-derived. */
const halls = dungeons.map((d) => {
  const boss = d.bossRelics.length
    ? `new[] { ${d.bossRelics.map((r) => `RelicId.${names.get(r)}`).join(", ")} }`
    : "NoRelics";
  return `            new DungeonDef(${d.id}, ${d.lvl}, "${d.name}", "${d.art}", ` +
         `${d.mult}, ${boss}, ${d.ghoolemBoss ? "true" : "false"}),`;
}).join("\n");

write("DungeonCatalog.cs", header(`${dungeons.length} halls`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One hall of the Hoard: what it is worth, and what its boss carries.</summary>
    public sealed class DungeonDef
    {
        /// <summary>Which hall this is, counting from one.</summary>
        public readonly int Tier;

        /// <summary>The delver level at which this hall is meant to be attempted.</summary>
        public readonly int Level;

        public readonly string Name;

        public readonly string Art;

        /// <summary>
        /// What a run in this hall is worth, applied to the foes inside it and to the score.
        /// </summary>
        /// <remarks>
        /// A table, not a formula. The first five entries are exact powers of 1.1 and the rest
        /// are rounded to four places — 1.6105 where the power is 1.61051 — so computing the
        /// power instead of reading this scores the deep halls a point out.
        /// </remarks>
        public readonly double Multiplier;

        /// <summary>The relic kit every boss in this hall carries.</summary>
        public readonly IReadOnlyList<RelicId> BossRelics;

        /// <summary>When set, the Ghoolem replaces this hall's bosses below the first floor.</summary>
        public readonly bool GhoolemBoss;

        public DungeonDef(int tier, int level, string name, string art, double multiplier,
            IReadOnlyList<RelicId> bossRelics, bool ghoolemBoss)
        {
            Tier = tier;
            Level = level;
            Name = name;
            Art = art;
            Multiplier = multiplier;
            BossRelics = bossRelics;
            GhoolemBoss = ghoolemBoss;
        }
    }

    /// <summary>The halls, in order.</summary>
    public static class DungeonCatalog
    {
        private static readonly RelicId[] NoRelics = new RelicId[0];

        public static readonly IReadOnlyList<DungeonDef> All = new List<DungeonDef>
        {
${halls}
        };

        /// <summary>
        /// The hall at this tier, clamped to the ones that exist — which is what the source
        /// does everywhere it reads the table, so a saved tier past the end still resolves.
        /// </summary>
        public static DungeonDef Get(int tier)
        {
            int i = tier - 1;
            if (i < 0) i = 0;
            if (i >= All.Count) i = All.Count - 1;
            return All[i];
        }
    }
}
`);

/* ---------- HeroPalette ---------- */

/* Role keys are single characters and several of them are punctuation, so they are emitted as
   escaped C# char literals rather than trusted to survive as source text. */
const asChar = (k) => {
  const c = [...k][0];
  const code = c.codePointAt(0);
  if (c === "'") return "'\\''";
  if (c === "\\") return "'\\\\'";
  return code >= 32 && code < 127 ? `'${c}'` : `'\\u${code.toString(16).padStart(4, "0")}'`;
};

const familyRows = palette.families.map((f) =>
  `            new ColourFamily("${f.name}", ${asChar(f.base)}, ${asChar(f.dark)}, ` +
  `${asChar(f.light)}, "${f.hex}"),`).join("\n");

const soloRows = Object.keys(palette.solos).map((k) =>
  `            { ${asChar(k)}, "${palette.solos[k]}" },`).join("\n");

const sh = palette.shade;

write("HeroPalette.cs", header(`${palette.families.length} colour families`) +
`
using System.Collections.Generic;

namespace RelicRun.Core.Content
{
    /// <summary>One family of the palette: a base colour, and the two it derives.</summary>
    /// <remarks>
    /// The three keys are what a hero's pixels actually hold. A pixel saying <c>H</c> is hair,
    /// <c>h</c> is hair in shadow and <c>1</c> is hair catching the light — so recolouring a
    /// delver is a matter of handing the shader three different colours, not three sprites.
    /// </remarks>
    public sealed class ColourFamily
    {
        public readonly string Name;

        /// <summary>The key a pixel of the base colour carries.</summary>
        public readonly char Base;

        /// <summary>The key for the shaded side, derived from the base.</summary>
        public readonly char Dark;

        /// <summary>The key for the lit side, derived from the base.</summary>
        public readonly char Light;

        /// <summary>What the family is when the delver has chosen nothing.</summary>
        public readonly string DefaultHex;

        public ColourFamily(string name, char baseKey, char dark, char light, string defaultHex)
        {
            Name = name;
            Base = baseKey;
            Dark = dark;
            Light = light;
            DefaultHex = defaultHex;
        }
    }

    /// <summary>
    /// How far a family's derived colours move from its base.
    /// </summary>
    /// <remarks>
    /// Shared by every family unless one says otherwise, and exposed as data because the sprite
    /// studio lets an artist tune it and watch the whole wardrobe follow.
    /// </remarks>
    public sealed class ShadeParams
    {
        public double DarkMultiplier = ${sh.darkMult};
        public double DarkHue = ${sh.darkHue};
        public double DarkSaturation = ${sh.darkSat};

        public double LightMultiplier = ${sh.lightMult};
        public double LightHue = ${sh.lightHue};
        public double LightSaturation = ${sh.lightSat};
    }

    /// <summary>The families, the fixed colours, and the palette they make together.</summary>
    public static class HeroPalette
    {
        public static readonly IReadOnlyList<ColourFamily> Families = new List<ColourFamily>
        {
${familyRows}
        };

        /// <summary>
        /// Colours that are never recoloured: white, black and five greys between them.
        /// </summary>
        public static readonly IReadOnlyDictionary<char, string> Fixed =
            new Dictionary<char, string>
        {
${soloRows}
        };

        /// <summary>
        /// The whole palette, as the shader wants it: every role key against its colour.
        /// </summary>
        /// <param name="chosen">
        /// A delver's own colours, keyed by a family's BASE key. Anything unstated keeps the
        /// family's default, which is how a half-dressed delver still comes out whole.
        /// </param>
        public static Dictionary<char, Rgb> Build(IReadOnlyDictionary<char, string> chosen = null,
            ShadeParams shade = null)
        {
            shade = shade ?? new ShadeParams();
            var roles = new Dictionary<char, Rgb>(Families.Count * 3 + Fixed.Count);

            for (int i = 0; i < Families.Count; i++)
            {
                ColourFamily family = Families[i];

                string picked;
                if (chosen == null || !chosen.TryGetValue(family.Base, out picked))
                {
                    picked = family.DefaultHex;
                }

                Rgb baseColour = Rgb.Parse(picked);
                roles[family.Base] = baseColour;
                roles[family.Dark] = HeroColour.ApplyShade(baseColour, shade.DarkMultiplier,
                    shade.DarkHue, shade.DarkSaturation);
                roles[family.Light] = HeroColour.ApplyShade(baseColour, shade.LightMultiplier,
                    shade.LightHue, shade.LightSaturation);
            }

            foreach (KeyValuePair<char, string> solo in Fixed)
            {
                roles[solo.Key] = Rgb.Parse(solo.Value);
            }

            return roles;
        }
    }
}
`);

console.log(`
  ${relics.length} relics, ${Object.keys(kinds).length} kinds, ` +
            `${channels.length} channels, ${trigList.length} triggers, ${emitList.length} emitters, ` +
            `${dungeons.length} halls, ${palette.families.length} colour families\n`);
