"""
Generated content — is the generator still the thing that wrote it?

    python Tools/check/generated.py

Every file under Core/Content opens with "Generated by Tools/extract/gen-csharp.mjs ... Do not
edit by hand". Three of them had been edited by hand anyway, and nothing said so: RelicText,
DungeonCatalog and EnemyCatalog had each grown a field of captured prose that the generator knew
nothing about. The files were right and the generator was months stale, so the next person to
run it — regenerating for an unrelated reason — would have silently deleted fifty-three lines of
prose and broken every caller. That is a landmine with a five-second fuse and no tripwire.

This is the tripwire. It runs the generator and asks git whether anything moved. A clean tree
before, a clean tree after, and the header's promise is true. It does not check the generator is
CORRECT — the content gates do that — only that it is the thing that produced what is committed.

Run it after touching Tools/extract/ or the corpus, and before believing a generated file.
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = os.path.join("Assets", "GameAssets", "Core", "Content")


def run(*args):
    """Runs a command at the repo root and returns (code, stdout)."""
    done = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, encoding="utf8",
                          errors="replace", shell=False)
    return done.returncode, (done.stdout or "") + (done.stderr or "")


def dirty():
    """
    Which generated files differ from what is staged.

    Against the index rather than against HEAD, so this can be run on work that is staged and
    about to be committed — which is exactly when the question matters. What it asks is "would
    running the generator change the files as they now stand", and a staged edit is part of how
    they now stand.
    """
    code, out = run("git", "diff", "--name-only", "--", GEN)

    if code != 0:
        print("  ! git could not be asked: " + out.strip())
        sys.exit(2)

    return [line.strip() for line in out.splitlines() if line.strip()]


def main():
    print("generated content")

    # An already-dirty file cannot be told apart from a stale generator afterwards, so this
    # refuses to guess rather than blaming the generator for somebody's work in progress.
    before = dirty()

    if before:
        print("  ! generated files were already modified before this ran:")
        for one in before:
            print("      " + one)
        print("  ! stage or revert them first; nothing can be concluded from here")
        sys.exit(2)

    code, out = run("node", os.path.join("Tools", "extract", "gen-csharp.mjs"))

    if code != 0:
        print("  ! the generator failed:")
        print(out.strip())
        sys.exit(1)

    after = dirty()

    if after:
        print("  ! the generator does not produce what is committed:")
        for one in after:
            print("      " + one)
        print("  ! either the file was edited by hand, or the generator is stale")
        print("  ! `git diff " + GEN + "` shows which")
        sys.exit(1)

    written = out.count("→")

    print("  regenerated " + str(written) + " files, all identical to what is committed")


if __name__ == "__main__":
    main()
